// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    
    #line 1 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class FormsSearchTemplate : FormsSearchTemplateBase
    {
        public virtual string TransformText()
        {
            
            #line 2 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    void GeneratePage(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("<%@ Page Title=\"");

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisit.SiteVisitName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\" Language=\"C#\" MasterPageFile=\"~/Site.master\" AutoEventWireup=\"true\" CodeBehind=" +
        "\"");

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Search.aspx.cs\" Inherits=\"OnSite.WebUI.SiteVisits.");

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"Search"" %>
<%@ Register Assembly=""DevExpress.Web.ASPxGridView.v12.1.Export, Version=12.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a""
    Namespace=""DevExpress.Web.ASPxGridView.Export"" TagPrefix=""dx"" %>
<asp:Content ID=""Content1"" ContentPlaceHolderID=""HeadContent"" runat=""server"">
</asp:Content>
<asp:Content ID=""Content2"" ContentPlaceHolderID=""MainContent"" runat=""server"">
	<table>
		<tr>
			<td>
				<dx:ASPxHyperLink ID=""lnkCreate"" runat=""server"" Text=""Create Building Contact"" NavigateUrl=""~/SiteVisits/");

        
        #line default
        #line hidden
        
        #line 32 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 32 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"Edit.aspx"">
				</dx:ASPxHyperLink>
			</td>
			<td>
				<dx:ASPxButton ID=""btnCsvExport"" runat=""server"" Text=""Export to Csv"" UseSubmitBehavior=""False"" />
			</td>
		</tr>
	</table>
    <dx:ASPxGridView ID=""ASPxGridView1"" runat=""server"" AutoGenerateColumns=""False"">
        <Columns>
            <dx:GridViewCommandColumn VisibleIndex=""0"">
                <CustomButtons>
                    <dx:GridViewCommandColumnCustomButton ID=""Edit"" Text=""Edit""></dx:GridViewCommandColumnCustomButton>
                    <dx:GridViewCommandColumnCustomButton ID=""Delete"" Text=""Delete""></dx:GridViewCommandColumnCustomButton>
                </CustomButtons>
                <ClearFilterButton Visible=""True"">
                </ClearFilterButton>
            </dx:GridViewCommandColumn>
            <dx:GridViewDataTextColumn FieldName=""");

        
        #line default
        #line hidden
        
        #line 50 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 50 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 50 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 50 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\"\r\n                ReadOnly=\"True\" VisibleIndex=\"0\" Visible=\"False\">\r\n\t\t\t</dx:Gri" +
        "dViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 53 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 53 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 54 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewExportColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 54 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
            <dx:GridViewDataTextColumn FieldName=""LocationLatitude"" 
                ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
			</dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn FieldName=""LocationLongitude"" 
                ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
			</dx:GridViewDataTextColumn>
        </Columns>
        <Settings ShowFilterRow=""True"" />
    </dx:ASPxGridView>
	<dx:ASPxGridViewExporter ID=""gridExport"" runat=""server"" GridViewID=""ASPxGridView1"">
    </dx:ASPxGridViewExporter>
</asp:Content>

");

        
        #line default
        #line hidden
        
        #line 68 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    }  

	private string GenerateGridViewColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) {

        
        #line default
        #line hidden
        
        #line 74 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 74 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 74 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 74 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 74 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\"\r\n                ReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 75 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldTabIndex));

        
        #line default
        #line hidden
        
        #line 75 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\">\r\n            </dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 77 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}

	private string GenerateGridViewExportColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitExportFields(form)) {
			string output = "";
			//checkbox columns
			if (field.ControlType.ControlTypeID == 1)
			{
				foreach(SiteVisitFormFieldItem item in field.SiteVisitFormFieldItems)
				{
					output += "\t\t\t<dx:GridViewDataTextColumn FieldName=\""+ field.FieldName +"_"+item.ListItemValue +"\" Caption=\""+item.ListItemLabel+"\" ReadOnly=\"True\" VisibleIndex=\""+ field.FieldTabIndex +"\" Visible=\"False\">\r\n\t\t\t</dx:GridViewDataTextColumn>\r\n";
				}
			}
			else 
			{
				output = "<dx:GridViewDataTextColumn FieldName=\""+ field.FieldName +"\" ReadOnly=\"True\" VisibleIndex=\""+ field.FieldTabIndex +"\" Visible=\"False\">\r\n\t\t\t</dx:GridViewDataTextColumn>";
			}


        
        #line default
        #line hidden
        
        #line 99 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 99 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(output));

        
        #line default
        #line hidden
        
        #line 99 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 100 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}

    void GenerateCodeFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 111 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using DevExpress.Web.ASPxClasses;
using OnSite.WebUI.Models;

namespace OnSite.WebUI.SiteVisits
{
    public partial class ");

        
        #line default
        #line hidden
        
        #line 124 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 124 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"Search : System.Web.UI.Page
    {
        SiteVisitDataEntities ctx = new SiteVisitDataEntities();

        protected void Page_Load(object sender, EventArgs e)
        {
			btnCsvExport.Click += new EventHandler(btnCsvExport_Click);
            ASPxGridView1.CustomButtonCallback += new DevExpress.Web.ASPxGridView.ASPxGridViewCustomButtonCallbackEventHandler(ASPxGridView1_CustomButtonCallback);
            ASPxGridView1_Bind();
        }

        protected void ASPxGridView1_Bind()
        {
            ASPxGridView1.DataSource = (from i in ctx.");

        
        #line default
        #line hidden
        
        #line 137 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 137 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
                                        select i);
            ASPxGridView1.DataBind();
        }

        protected void ASPxGridView1_CustomButtonCallback(object sender, DevExpress.Web.ASPxGridView.ASPxGridViewCustomButtonCallbackEventArgs e)
        {
            if (e.ButtonID == ""Edit"")
            {
                string id = ASPxGridView1.GetRowValues(e.VisibleIndex, """);

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\").ToString();\r\n                ASPxWebControl.RedirectOnCallback(\"");

        
        #line default
        #line hidden
        
        #line 147 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisit.SiteVisitName));

        
        #line default
        #line hidden
        
        #line 147 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Edit.aspx?ID=\"+id);\r\n            } \r\n            else if (e.ButtonID == \"Delete\")" +
        "\r\n            {\r\n                SiteVisitDataEntities ctx = new SiteVisitDataEn" +
        "tities();\r\n                int id = (int)ASPxGridView1.GetRowValues(e.VisibleInd" +
        "ex, \"");

        
        #line default
        #line hidden
        
        #line 152 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 152 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\");\r\n\r\n                var record = (from b in ctx.");

        
        #line default
        #line hidden
        
        #line 154 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 154 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n                              where b.");

        
        #line default
        #line hidden
        
        #line 155 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 155 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@" == id
                              select b).FirstOrDefault();

                ctx.DeleteObject(record);
                ctx.SaveChanges();
                ASPxGridView1.DataBind();
            }
   
        }

        protected void btnCsvExport_Click(object sender, EventArgs e)
        {
			ASPxGridView1.Columns[""");

        
        #line default
        #line hidden
        
        #line 167 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 167 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\"].Visible = true;\r\n");

        
        #line default
        #line hidden
        
        #line 168 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateExportColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 168 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n\t\t\tASPxGridView1.DataBind();\r\n            gridExport.WriteCsvToResponse();\r\n   " +
        "     }\r\n    }\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 174 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    }

	private string GenerateExportColumns(SiteVisitForm form)
	{

		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitExportFields(form)) {
			string output = "";
			//checkbox columns
			if (field.ControlType.ControlTypeID == 1)
			{
				foreach(SiteVisitFormFieldItem item in field.SiteVisitFormFieldItems)
				{
					output += "ASPxGridView1.Columns[\""+ field.FieldName +"_"+item.ListItemValue +"\"].Visible = true;\r\n";
				}
			}
			else 
			{
				output = "ASPxGridView1.Columns[\""+ field.FieldName +"\"].Visible = true;";
			}

        
        #line default
        #line hidden
        
        #line 194 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 194 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(output));

        
        #line default
        #line hidden
        
        #line 194 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 195 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}
	

	void GenerateDesignerFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
	{
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");

        
        #line default
        #line hidden
        
        #line 204 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.SiteVisits {
    
    
    public partial class ");

        
        #line default
        #line hidden
        
        #line 217 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 217 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Search {\r\n\r\n                /// <summary>\r\n        /// lnkCreate control.\r\n      " +
        "  /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n    " +
        "    /// To modify move field declaration from designer file to code-behind file." +
        "\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.ASPxEditors.A" +
        "SPxHyperLink lnkCreate;\r\n        \r\n\t\t/// <summary>\r\n        /// btnXLSExport con" +
        "trol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated" +
        " field.\r\n        /// To modify move field declaration from designer file to code" +
        "-behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web." +
        "ASPxEditors.ASPxButton btnCsvExport;\r\n\r\n        /// <summary>\r\n        /// ASPxG" +
        "ridView1 control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Au" +
        "to-generated field.\r\n        /// To modify move field declaration from designer " +
        "file to code-behind file.\r\n        /// </remarks>\r\n        protected global::Dev" +
        "Express.Web.ASPxGridView.ASPxGridView ASPxGridView1;\r\n        \r\n        /// <sum" +
        "mary>\r\n        /// Edit control.\r\n        /// </summary>\r\n        /// <remarks>\r" +
        "\n        /// Auto-generated field.\r\n        /// To modify move field declaration" +
        " from designer file to code-behind file.\r\n        /// </remarks>\r\n        protec" +
        "ted global::DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton Edit;\r" +
        "\n        \r\n        /// <summary>\r\n        /// Delete control.\r\n        /// </sum" +
        "mary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To " +
        "modify move field declaration from designer file to code-behind file.\r\n        /" +
        "// </remarks>\r\n        protected global::DevExpress.Web.ASPxGridView.GridViewCom" +
        "mandColumnCustomButton Delete;\r\n        \r\n        /// <summary>\r\n        /// gri" +
        "dExport control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Aut" +
        "o-generated field.\r\n        /// To modify move field declaration from designer f" +
        "ile to code-behind file.\r\n        /// </remarks>\r\n        protected global::DevE" +
        "xpress.Web.ASPxGridView.Export.ASPxGridViewExporter gridExport;\r\n\r\n//GenerateDes" +
        "ignerProperties(forms) \r\n\r\n\r\n\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 278 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

	}

	private string GenerateDesignerProperties(IEnumerable<SiteVisitForm> forms)
	{
		foreach(SiteVisitForm form in forms) {

        
        #line default
        #line hidden
        
        #line 284 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("        /// <summary>\r\n        /// uc");

        
        #line default
        #line hidden
        
        #line 286 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 286 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(" control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-genera" +
        "ted field.\r\n        /// To modify move field declaration from designer file to c" +
        "ode-behind file.\r\n        /// </remarks>\r\n        protected global::OnSite.WebUI" +
        ".ClientForms.");

        
        #line default
        #line hidden
        
        #line 292 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 292 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(" uc");

        
        #line default
        #line hidden
        
        #line 292 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 292 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 293 "C:\Apps\On-Site\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class FormsSearchTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
