// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class FormsChildSearchTemplate : FormsChildSearchTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 2 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisitForm);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisitForm);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisitForm);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"

    void GeneratePage(SiteVisitForm form)
    {
		string siteVisitName = StringSanitizer.SanitizeForCode(form.SiteVisit.SiteVisitName);
		string formName = siteVisitName;
		var parentForm = form.SiteVisitForm1;
		string table = siteVisitName + "_" + form.DBTableName;
        string pkey = siteVisitName + "_" + form.DBPrimaryKeyName;
		string ftable = siteVisitName + "_" + parentForm.DBTableName;
		string fkey = siteVisitName + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 26 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("<%@ Control Language=\"C#\" AutoEventWireup=\"true\" CodeBehind=\"");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("Search.ascx.cs\" Inherits=\"OnSite.WebUI.ClientCode.UserControls.");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("Search\" %>\r\n<%@ Register Assembly=\"DevExpress.Web.v13.1, Version=13.1.4.0, Cultur" +
        "e=neutral, PublicKeyToken=b88d1754d700e49a\" Namespace=\"DevExpress.Web.ASPxGridVi" +
        "ew.Export\" TagPrefix=\"dx\" %>\r\n<asp:HiddenField ID=\"hf");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey\" runat=\"server\" />\r\n<div class=\"formGroupFieldLabel\">");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"</div>
<table>
    <tr>
        <td>
            <dx:ASPxButton ID=""btnCreate"" runat=""server"" Text=""Add New Row"" Image-Url=""~/Images/add.png"" AutoPostBack=""false"">
            </dx:ASPxButton>
        </td>
        <td>
            <dx:ASPxButton ID=""btnRefresh"" runat=""server"" Text=""Refresh"" AutoPostBack=""false"" Image-Url=""~/Images/arrow_refresh.png"">
                <ClientSideEvents Click=""function(s,e){gv");

        
        #line default
        #line hidden
        
        #line 39 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 39 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".PerformCallback();}\" />\r\n            </dx:ASPxButton>\r\n        </td><%--\r\n\t\t<td>" +
        "\r\n\t\t\t<dx:ASPxButton ID=\"btnCsvExport\" runat=\"server\" Text=\"Export to Csv\" UseSub" +
        "mitBehavior=\"False\" />\r\n\t\t</td>--%>\r\n    </tr>\r\n</table>\r\n\r\n<dx:ASPxGridView ID=" +
        "\"gv");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" runat=\"server\" AutoGenerateColumns=\"False\" ClientInstanceName=\"gv");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" \r\n    DataSourceID=\"");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("DataSource\" KeyFieldName=\"");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@""">
    <Columns>
        <dx:GridViewCommandColumn VisibleIndex=""0"">
            <CustomButtons>
                <dx:GridViewCommandColumnCustomButton ID=""Edit"" Text=""Edit""></dx:GridViewCommandColumnCustomButton>
                <dx:GridViewCommandColumnCustomButton ID=""Delete"" Text=""Delete""></dx:GridViewCommandColumnCustomButton>
            </CustomButtons>
            <ClearFilterButton Visible=""True"">
            </ClearFilterButton>
        </dx:GridViewCommandColumn>
        <dx:GridViewDataTextColumn FieldName=""");

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" Caption=\"ID\" ReadOnly=\"True\" Visible=\"false\" VisibleIndex=\"0\">\r\n        </dx:Gr" +
        "idViewDataTextColumn>\r\n        <dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@""" VisibleIndex=""1"" Visible=""false"">
        </dx:GridViewDataTextColumn>
		<dx:GridViewDataTextColumn Caption=""Row"" ReadOnly=""True"" UnboundType=""String"" VisibleIndex=""2"">
            <Settings AllowAutoFilter=""False"" AllowAutoFilterTextInputTimer=""False"" 
                AllowDragDrop=""False"" AllowGroup=""False"" AllowHeaderFilter=""False"" 
                AllowSort=""False"" />
        </dx:GridViewDataTextColumn>
");

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewColumns(form, 3)));

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\r\n    </Columns>\r\n    <Settings ShowFilterRow=\"True\" ShowHeaderFilterButton=\"true" +
        "\" />\r\n\t<SettingsBehavior AllowSelectByRowClick=\"true\" AllowSelectSingleRowOnly=\"" +
        "true\" />\r\n\t<ClientSideEvents RowClick=\"function(s,e){window.open(\'");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("Edit.aspx?ID=\'+gv");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".GetRowKey(e.visibleIndex));}\" CustomButtonClick=\"function(s,e) {if (e.buttonID =" +
        "= \'Delete\'){e.processOnServer = confirm(\'Are you sure you want to delete this it" +
        "em?\');} else {e.processOnServer = false;var id = gv");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".GetRowKey(e.visibleIndex);window.open(\'");

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 72 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("Edit.aspx?ID=\'+id);} }\" />\r\n</dx:ASPxGridView>\r\n\r\n<asp:EntityDataSource ID=\"");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("DataSource\" runat=\"server\" \r\n    ConnectionString=\"name=SiteVisitDataEntities\" \r\n" +
        "    DefaultContainerName=\"SiteVisitDataEntities\" EnableDelete=\"True\" \r\n    Enabl" +
        "eFlattening=\"False\" EntitySetName=\"");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" \r\n    EntityTypeFilter=\"\" Select=\"\" Where=\"it.");

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(" = @");

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\">\r\n    <WhereParameters>\r\n        <asp:ControlParameter ControlID=\"hf");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey\" DefaultValue=\"0\" \r\n            Name=\"");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" PropertyName=\"Value\" Type=\"Int16\" />\r\n    </WhereParameters>\r\n</asp:EntityDataS" +
        "ource>\r\n \r\n<dx:ASPxGridViewExporter ID=\"gridExport\" runat=\"server\" GridViewID=\"g" +
        "v");

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 86 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\">\r\n</dx:ASPxGridViewExporter>\r\n<br />\r\n");

        
        #line default
        #line hidden
        
        #line 89 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"

    } 
	
	private string GenerateGridViewColumns(SiteVisitForm form, int startIndex)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) 
		{
			ControlType.UIType uiType = (ControlType.UIType)Enum.Parse(typeof(ControlType.UIType), field.ControlType.UITypeName);
			string dataItemTemplate = "";
			if (uiType == ControlType.UIType.RadioList)
            {
				dataItemTemplate = "<DataItemTemplate><dx:ASPxLabel ID=\"label\" runat=\"server\" Text=\"<%# GetFieldLabel(Container,&quot;" + field.FieldName + "&quot;) %>\"></dx:ASPxLabel></DataItemTemplate>";
            }
			else if (uiType == ControlType.UIType.Currency)
            {
				//format for currency
				dataItemTemplate = "<PropertiesTextEdit DisplayFormatString=\"c\" />";
            }


        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\"\r\n                ReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(startIndex++));

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\">\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataItemTemplate));

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\r\n            </dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 112 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
 
		}
		return "";
	}

    void GenerateCodeFile(SiteVisitForm form)
    {
		string siteVisitName = StringSanitizer.SanitizeForCode(form.SiteVisit.SiteVisitName);
		string formName = siteVisitName;
		var parentForm = form.SiteVisitForm1;
		string table = siteVisitName + "_" + form.DBTableName;
        string pkey = siteVisitName + "_" + form.DBPrimaryKeyName;
		string ftable = siteVisitName + "_" + parentForm.DBTableName;
		string fkey = siteVisitName + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 126 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.Objects;
using DevExpress.Web.ASPxClasses;
using DevExpress.Web.ASPxGridView;
using DevExpress.Web.ASPxEditors;
using OnSite.WebUI.ClientCode.Models;
using OnSite.WebUI.Models;
using OnSite.WebUI.Classes;

namespace OnSite.WebUI.ClientCode.UserControls
{
    public partial class ");

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 144 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"Search : System.Web.UI.UserControl
    {
		SiteVisitDataEntities ctx = new SiteVisitDataEntities();

		#region Unused Properties
		public string OnChangeFunctionName { get; set; }
        public string CheckStateFunctionName { get; set; }
        public bool IsRequired { get; set; }
        public bool IsEnabled { get; set; }
		public string RequiredFieldErrorMessage { get; set; }
		#endregion

		#region Public Methods
        public void BindListControls()
        {
            //nothing to bind.
        }

        public void LoadForm(");

        
        #line default
        #line hidden
        
        #line 162 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ftable));

        
        #line default
        #line hidden
        
        #line 162 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(" parentForm)\r\n        {\r\n            hf");

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey.Value = parentForm.");

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 164 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".ToString();\r\n            btnCreate.ClientSideEvents.Click = \"function(s,e){windo" +
        "w.open(\'");

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("Edit.aspx?PID=\" + hf");

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 165 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey.Value + \"\');}\";\r\n            gv");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@".DataBind();
        }

        public void SaveForm(int id)
        {
            //nothing to save.
        }
        #endregion

        protected int? getParentKey()
        {
            int? retVal = null;
            if (!string.IsNullOrEmpty(hf");

        
        #line default
        #line hidden
        
        #line 178 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 178 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey.Value))\r\n                retVal = (int?)int.Parse(hf");

        
        #line default
        #line hidden
        
        #line 179 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 179 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("FormKey.Value);\r\n            return retVal;\r\n        }\r\n\r\n        protected void " +
        "Page_Init(object sender, EventArgs e)\r\n        {\r\n            gv");

        
        #line default
        #line hidden
        
        #line 185 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 185 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".CustomCallback += new DevExpress.Web.ASPxGridView.ASPxGridViewCustomCallbackEven" +
        "tHandler(gv");

        
        #line default
        #line hidden
        
        #line 185 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 185 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("_CustomCallback);\r\n\t\t\tgv");

        
        #line default
        #line hidden
        
        #line 186 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 186 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".CustomButtonCallback += new DevExpress.Web.ASPxGridView.ASPxGridViewCustomButton" +
        "CallbackEventHandler(gv");

        
        #line default
        #line hidden
        
        #line 186 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 186 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("_CustomButtonCallback);\r\n\t\t\tgv");

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".CustomColumnDisplayText += new ASPxGridViewColumnDisplayTextEventHandler(gv");

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("_CustomColumnDisplayText);\r\n        }\r\n\r\n        protected void gv");

        
        #line default
        #line hidden
        
        #line 190 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 190 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("_CustomCallback(object sender, DevExpress.Web.ASPxGridView.ASPxGridViewCustomCall" +
        "backEventArgs e)\r\n        {\r\n            gv");

        
        #line default
        #line hidden
        
        #line 192 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 192 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".DataBind();\r\n        }\r\n\r\n\t\tprotected void gv");

        
        #line default
        #line hidden
        
        #line 195 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 195 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("_CustomButtonCallback(object sender, DevExpress.Web.ASPxGridView.ASPxGridViewCust" +
        "omButtonCallbackEventArgs e)\r\n        {\r\n            if (e.ButtonID == \"Delete\")" +
        "\r\n            {\r\n                int id = (int)gv");

        
        #line default
        #line hidden
        
        #line 199 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 199 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".GetRowValues(e.VisibleIndex, \"");

        
        #line default
        #line hidden
        
        #line 199 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 199 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\");\r\n\r\n                var record = (from b in ctx.");

        
        #line default
        #line hidden
        
        #line 201 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 201 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\r\n                              where b.");

        
        #line default
        #line hidden
        
        #line 202 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 202 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(" == id\r\n                              select b).FirstOrDefault();\r\n\r\n            " +
        "    ctx.DeleteObject(record);\r\n                ctx.SaveChanges();\r\n             " +
        "   gv");

        
        #line default
        #line hidden
        
        #line 207 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 207 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".DataBind();\r\n            }\r\n   \r\n        }\r\n\r\n\t\tprotected void gv");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"_CustomColumnDisplayText(object sender, ASPxGridViewColumnDisplayTextEventArgs e)
        {
            if (e.Column.Caption == ""Row"")
            {
                e.DisplayText = (e.VisibleRowIndex + 1).ToString();
            }
        }

        protected void btnCsvExport_Click(object sender, EventArgs e)
        {
            gv");

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".Columns[\"");

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey));

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\"].Visible = true;\r\n            gv");

        
        #line default
        #line hidden
        
        #line 223 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 223 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".Columns[\"");

        
        #line default
        #line hidden
        
        #line 223 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 223 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\"].Visible = true;\r\n\r\n            gv");

        
        #line default
        #line hidden
        
        #line 225 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 225 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".DataBind();\r\n            gridExport.FileName = \"");

        
        #line default
        #line hidden
        
        #line 226 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 226 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\";\r\n            gridExport.WriteCsvToResponse();\r\n        }   \r\n\r\n\t\tprotected str" +
        "ing GetFieldLabel(GridViewDataItemTemplateContainer container, string fieldName)" +
        "\r\n        {\r\n            int id = (int)gv");

        
        #line default
        #line hidden
        
        #line 232 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 232 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".GetRowValues(container.VisibleIndex, \"");

        
        #line default
        #line hidden
        
        #line 232 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 232 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\");\r\n            string fieldValue = (string)gv");

        
        #line default
        #line hidden
        
        #line 233 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 233 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(".GetRowValues(container.VisibleIndex, fieldName);\r\n            string fieldLabel " +
        "= \"\";\r\n\t\t\tif (!string.IsNullOrEmpty(fieldValue))\r\n            {\r\n\t\t\t\tvar sql = \"" +
        "SELECT VALUE SiteVisitDataModel.Store.ListItemGetFieldLabel(\'");

        
        #line default
        #line hidden
        
        #line 237 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 237 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write("\',\'\" + fieldName + \"\',@FieldItemValue) FROM {1}\";\r\n\t\t\t\tfieldLabel = ctx.CreateQue" +
        "ry<string>(sql, new ObjectParameter(\"FieldItemValue\", fieldValue)).FirstOrDefaul" +
        "t();\r\n\t\t\t}\r\n            return fieldLabel;\r\n        }\r\n\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 244 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"

    }


	void GenerateDesignerFile(SiteVisitForm form)
    {
		string sitevisitname = form.SiteVisit.SiteVisitName.Replace(" ", "");
		string formName = form.SiteVisitFormName.Replace(" ", "");
		var parentForm = form.SiteVisitForm1;
		string table = sitevisitname + "_" + form.DBTableName;
        string pkey = sitevisitname + "_" + form.DBPrimaryKeyName;
		string ftable = sitevisitname + "_" + parentForm.DBTableName;
		string fkey = sitevisitname + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 257 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.ClientCode.UserControls {
    
    
    public partial class ");

        
        #line default
        #line hidden
        
        #line 270 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 270 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"Search {

		/// <summary>
        /// hfLaundyCyclesFormKey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hf");

        
        #line default
        #line hidden
        
        #line 279 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 279 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"FormKey;
        
        /// <summary>
        /// btnCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton btnCreate;
        
        /// <summary>
        /// btnRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxButton btnRefresh;
        
        /// <summary>
        /// gvLaundryCycles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gv");

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@";
        
        /// <summary>
        /// LaundryCyclesDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.EntityDataSource ");

        
        #line default
        #line hidden
        
        #line 315 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 315 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"
this.Write(@"DataSource;
        
        /// <summary>
        /// gridExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter gridExport;

	}
}
");

        
        #line default
        #line hidden
        
        #line 328 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsChildSearchTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class FormsChildSearchTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
