// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class FormsSearchTemplate : FormsSearchTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 2 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    void GeneratePage(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("<%@ Page Title=\"");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parentForm.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(" Search\" Language=\"C#\" MasterPageFile=\"~/Site.master\" AutoEventWireup=\"true\" Code" +
        "Behind=\"");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Search.aspx.cs\" Inherits=\"OnSite.WebUI.ClientCode.SiteVisits.");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"Search"" %>
<%@ Register Assembly=""DevExpress.Web.v13.1, Version=13.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a"" Namespace=""DevExpress.Web.ASPxGridView.Export"" TagPrefix=""dx"" %>
<asp:Content ID=""Content1"" ContentPlaceHolderID=""HeadContent"" runat=""server"">
<script type=""text/javascript"">
	var eEvent;
	function OnCustomButtonClick(s,e) {
		if (e.buttonID == 'Delete'){ 
			e.processOnServer = confirm('Are you sure you want to delete this item?');
		} else {
			e.processOnServer = false;
			var id = grid.GetRowKey(e.visibleIndex);
			window.open(""");

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 34 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Edit.aspx?ID=\"+id);\r\n\t\t}\r\n\t}\r\n\r\n\tfunction OnRowClick(s,e) {\r\n\t\tvar id = grid.GetR" +
        "owKey(e.visibleIndex);\r\n\t\twindow.open(\"");

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Edit.aspx?ID=\"+id);\r\n\t}\r\n\r\n\tfunction OnCreateClick(s,e) {\r\n\t\twindow.open(\"");

        
        #line default
        #line hidden
        
        #line 44 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 44 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Edit.aspx\");\r\n\t}\r\n</script>\r\n</asp:Content>\r\n<asp:Content ID=\"Content2\" ContentPl" +
        "aceHolderID=\"MainContent\" runat=\"server\">\r\n\t<h2>Search ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parentForm.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("s</h2>\r\n\t<table>\r\n\t\t<tr>\r\n\t\t\t<td>\r\n\t\t\t\t<dx:ASPxButton ID=\"lnkCreate\" runat=\"serve" +
        "r\" Text=\"Add New ");

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parentForm.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@""" UseSubmitBehavior=""False"" Image-Url=""~/Images/add.png"">
					<ClientSideEvents Click=""OnCreateClick"" />
				</dx:ASPxButton>
			</td>
			<td>
				<dx:ASPxButton ID=""btnCsvExport"" runat=""server"" Text=""Export to Csv"" Image-Url=""~/Images/page_excel.png"" UseSubmitBehavior=""False"" />
			</td>
		</tr>
	</table>
    <dx:ASPxGridView ID=""ASPxGridView1"" runat=""server"" AutoGenerateColumns=""False"" 
		DataSourceID=""");

        
        #line default
        #line hidden
        
        #line 63 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 63 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("DataSource\" \r\n\t\tKeyFieldName=\"");

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 64 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"""
		ClientInstanceName=""grid"">
        <Columns>
            <dx:GridViewCommandColumn VisibleIndex=""0"">
                <CustomButtons>
                    <dx:GridViewCommandColumnCustomButton ID=""Edit"" Text=""Edit""></dx:GridViewCommandColumnCustomButton>
                    <dx:GridViewCommandColumnCustomButton ID=""Delete"" Text=""Delete""></dx:GridViewCommandColumnCustomButton>
                </CustomButtons>
                <ClearFilterButton Visible=""True"">
                </ClearFilterButton>
            </dx:GridViewCommandColumn>
            <dx:GridViewDataTextColumn FieldName=""");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"""
                ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
			</dx:GridViewDataTextColumn>
			<dx:GridViewDataComboBoxColumn FieldName=""DispositionID"" Caption=""Disposition"" ReadOnly=""True"" VisibleIndex=""0"" Visible=""true"">
				<PropertiesComboBox DataSourceID=""DispositionsDataSource"" ValueField=""DispositionID"" IncrementalFilteringMode=""StartsWith"" TextField=""DispositionName"" ValueType=""System.Int32"" DropDownStyle=""DropDown"" />
			</dx:GridViewDataComboBoxColumn>
");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewExportColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
            <dx:GridViewDataTextColumn FieldName=""LocationLatitude"" 
                ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
			</dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn FieldName=""LocationLongitude"" 
                ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
			</dx:GridViewDataTextColumn>
        </Columns>
        <Settings ShowFilterRow=""True"" ShowHeaderFilterButton=""true"" />
		<SettingsBehavior AllowSelectByRowClick=""true"" AllowSelectSingleRowOnly=""true"" />
		<ClientSideEvents CustomButtonClick=""OnCustomButtonClick"" RowClick=""OnRowClick"" />
    </dx:ASPxGridView>
    <asp:EntityDataSource ID=""");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"DataSource"" runat=""server"" 
        ConnectionString=""name=SiteVisitDataEntities"" 
        DefaultContainerName=""SiteVisitDataEntities"" EnableFlattening=""False"" 
        ContextTypeName=""OnSite.WebUI.ClientCode.Models.SiteVisitDataEntities""
        EntitySetName=""");

        
        #line default
        #line hidden
        
        #line 98 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 98 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@""">
    </asp:EntityDataSource>
	<asp:EntityDataSource ID=""DispositionsDataSource"" runat=""server"" 
		ConnectionString=""name=SiteVisitDataEntities"" DefaultContainerName=""SiteVisitDataEntities"" 
        ContextTypeName=""OnSite.WebUI.ClientCode.Models.SiteVisitDataEntities""
		EnableFlattening=""False"" EntitySetName=""Dispositions"">
	</asp:EntityDataSource> 
	<dx:ASPxGridViewExporter ID=""gridExport"" runat=""server"" GridViewID=""ASPxGridView1"">
    </dx:ASPxGridViewExporter>
</asp:Content>

");

        
        #line default
        #line hidden
        
        #line 109 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    }  

	private string GenerateGridViewColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) {

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\"\r\n                ReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldTabIndex));

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\">\r\n            </dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}

	private string GenerateGridViewExportColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitExportFields(form)) {
			string output = "";
			//checkbox columns
			if (field.ControlType.ControlTypeID == 1)
			{
				foreach(SiteVisitFormFieldItem item in field.SiteVisitFormFieldItems)
				{
					output += "\t\t\t<dx:GridViewDataTextColumn FieldName=\""+ field.FieldName +"_"+item.ListItemValue +"\" Caption=\""+item.ListItemLabel+"\" ReadOnly=\"True\" VisibleIndex=\""+ field.FieldTabIndex +"\" Visible=\"False\">\r\n\t\t\t</dx:GridViewDataTextColumn>\r\n";
				}
			}
			else 
			{
				output = "<dx:GridViewDataTextColumn FieldName=\""+ field.FieldName +"\" ReadOnly=\"True\" VisibleIndex=\""+ field.FieldTabIndex +"\" Visible=\"False\">\r\n\t\t\t</dx:GridViewDataTextColumn>";
			}


        
        #line default
        #line hidden
        
        #line 140 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 140 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(output));

        
        #line default
        #line hidden
        
        #line 140 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 141 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}

    void GenerateCodeFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 152 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using DevExpress.Web.ASPxClasses;
using OnSite.WebUI.ClientCode.Models;
using OnSite.WebUI.Models;

namespace OnSite.WebUI.ClientCode.SiteVisits
{
    public partial class ");

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"Search : System.Web.UI.Page
    {
        SiteVisitDataEntities ctx = new SiteVisitDataEntities();

        protected void Page_Load(object sender, EventArgs e)
        {
			btnCsvExport.Click += new EventHandler(btnCsvExport_Click);
            ASPxGridView1.CustomButtonCallback += new DevExpress.Web.ASPxGridView.ASPxGridViewCustomButtonCallbackEventHandler(ASPxGridView1_CustomButtonCallback);
            //ASPxGridView1_Bind();
        }

        protected void ASPxGridView1_Bind()
        {
            //ASPxGridView1.DataSource = (from i in ctx.");

        
        #line default
        #line hidden
        
        #line 179 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 179 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"
            //                            select i);
            //ASPxGridView1.DataBind();
        }

        protected void ASPxGridView1_CustomButtonCallback(object sender, DevExpress.Web.ASPxGridView.ASPxGridViewCustomButtonCallbackEventArgs e)
        {
            if (e.ButtonID == ""Edit"")
            {
                string id = ASPxGridView1.GetRowValues(e.VisibleIndex, """);

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 188 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\").ToString();\r\n                ASPxWebControl.RedirectOnCallback(\"");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Edit.aspx?ID=\"+id);\r\n            } \r\n            else if (e.ButtonID == \"Delete\")" +
        "\r\n            {\r\n                SiteVisitDataEntities ctx = new SiteVisitDataEn" +
        "tities();\r\n                int id = (int)ASPxGridView1.GetRowValues(e.VisibleInd" +
        "ex, \"");

        
        #line default
        #line hidden
        
        #line 194 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 194 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\");\r\n\r\n                var record = (from b in ctx.");

        
        #line default
        #line hidden
        
        #line 196 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 196 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n                              where b.");

        
        #line default
        #line hidden
        
        #line 197 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 197 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@" == id
                              select b).FirstOrDefault();

                ctx.DeleteObject(record);
                ctx.SaveChanges();
                ASPxGridView1.DataBind();
            }
   
        }

        protected void btnCsvExport_Click(object sender, EventArgs e)
        {
			ASPxGridView1.Columns[""");

        
        #line default
        #line hidden
        
        #line 209 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 209 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\"].Visible = true;\r\n");

        
        #line default
        #line hidden
        
        #line 210 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateExportColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 210 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n\t\t\tASPxGridView1.DataBind();\r\n\t\t\tgridExport.FileName = \"");

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 212 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\";\r\n            gridExport.WriteCsvToResponse();\r\n        }\r\n    }\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 217 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

    }

	private string GenerateExportColumns(SiteVisitForm form)
	{

		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitExportFields(form)) {
			string output = "";
			//checkbox columns
			if (field.ControlType.ControlTypeID == 1)
			{
				foreach(SiteVisitFormFieldItem item in field.SiteVisitFormFieldItems)
				{
					output += "ASPxGridView1.Columns[\""+ field.FieldName +"_"+item.ListItemValue +"\"].Visible = true;\r\n";
				}
			}
			else 
			{
				output = "ASPxGridView1.Columns[\""+ field.FieldName +"\"].Visible = true;";
			}

        
        #line default
        #line hidden
        
        #line 237 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 237 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(output));

        
        #line default
        #line hidden
        
        #line 237 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 238 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
 
		}
		return "";
	}
	

	void GenerateDesignerFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
	{
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");

        
        #line default
        #line hidden
        
        #line 247 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.ClientCode.SiteVisits {
    
    
    public partial class ");

        
        #line default
        #line hidden
        
        #line 260 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 260 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"
this.Write("Search {\r\n\r\n        /// <summary>\r\n        /// lnkCreate control.\r\n        /// </" +
        "summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        /// " +
        "To modify move field declaration from designer file to code-behind file.\r\n      " +
        "  /// </remarks>\r\n        protected global::DevExpress.Web.ASPxEditors.ASPxButto" +
        "n lnkCreate;\r\n        \r\n\t\t/// <summary>\r\n        /// btnXLSExport control.\r\n    " +
        "    /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n  " +
        "      /// To modify move field declaration from designer file to code-behind fil" +
        "e.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.ASPxEditors" +
        ".ASPxButton btnCsvExport;\r\n\r\n        /// <summary>\r\n        /// ASPxGridView1 co" +
        "ntrol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generate" +
        "d field.\r\n        /// To modify move field declaration from designer file to cod" +
        "e-behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web" +
        ".ASPxGridView.ASPxGridView ASPxGridView1;\r\n        \r\n        /// <summary>\r\n    " +
        "    /// Edit control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        //" +
        "/ Auto-generated field.\r\n        /// To modify move field declaration from desig" +
        "ner file to code-behind file.\r\n        /// </remarks>\r\n        protected global:" +
        ":DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton Edit;\r\n\r\n\t\t/// <s" +
        "ummary>\r\n        /// DispositionsDataSource control.\r\n        /// </summary>\r\n  " +
        "      /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To modify mo" +
        "ve field declaration from designer file to code-behind file.\r\n        /// </rema" +
        "rks>\r\n        protected global::System.Web.UI.WebControls.EntityDataSource Dispo" +
        "sitionsDataSource;\r\n        \r\n        /// <summary>\r\n        /// Delete control." +
        "\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated fiel" +
        "d.\r\n        /// To modify move field declaration from designer file to code-behi" +
        "nd file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.ASPxG" +
        "ridView.GridViewCommandColumnCustomButton Delete;\r\n        \r\n        /// <summar" +
        "y>\r\n        /// gridExport control.\r\n        /// </summary>\r\n        /// <remark" +
        "s>\r\n        /// Auto-generated field.\r\n        /// To modify move field declarat" +
        "ion from designer file to code-behind file.\r\n        /// </remarks>\r\n        pro" +
        "tected global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter gridExpor" +
        "t;\r\n\r\n\r\n\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 328 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\FormsSearchTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class FormsSearchTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
