// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    
    #line 1 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ReportMasterScheduleTemplate : ReportMasterScheduleTemplateBase
    {
        public virtual string TransformText()
        {
            
            #line 2 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"

    void GeneratePage(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;
				SiteVisitFormField reportViewerFilterField = SiteVisitDBHelper.GetSiteVisitReportViewerFilterField(parentForm);
		string reportViewerFilterExpression = "", whereParameters = "";
		if (reportViewerFilterField != null)
		{
			reportViewerFilterExpression = "(it." + table + "." + reportViewerFilterField.FieldName + " = @ReportViewerFilterValue OR @ReportViewerFilterValue IS NULL OR @ReportViewerFilterValue = '')";
			whereParameters = @"<WhereParameters>
            <asp:ProfileParameter Name=""ReportViewerFilterValue"" PropertyName=""ReportViewerFilterValue"" Type=""String"" />
        </WhereParameters>";
		}		

        
        #line default
        #line hidden
        
        #line 32 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("<%@ Page Title=\"");

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisit.SiteVisitName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" Language=\"C#\" MasterPageFile=\"~/Site.master\" AutoEventWireup=\"true\" CodeBehind=" +
        "\"Master");

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Schedule.aspx.cs\" Inherits=\"OnSite.WebUI.ClientCode.Reports.Master");

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 33 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Schedule\" %>\r\n<%@ Register Assembly=\"DevExpress.Web.ASPxScheduler.v12.1, Version=" +
        "12.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a\"\r\n    Namespace=\"DevE" +
        "xpress.Web.ASPxScheduler\" TagPrefix=\"dxwschs\" %>\r\n<%@ Register assembly=\"DevExpr" +
        "ess.XtraScheduler.v12.1.Core, Version=12.1.4.0, Culture=neutral, PublicKeyToken=" +
        "b88d1754d700e49a\" namespace=\"DevExpress.XtraScheduler\" tagprefix=\"dx\" %>\r\n<asp:C" +
        "ontent ID=\"Content1\" ContentPlaceHolderID=\"HeadContent\" runat=\"server\">\r\n<script" +
        " type=\"text/javascript\">\r\n    // <![CDATA[\r\n        function OnAppointmentsSelec" +
        "tionChanged(scheduler, appointmentIds) {\r\n            if(appointmentIds != null " +
        "&& appointmentIds.length == 1) {\r\n                scheduler.GetAppointmentProper" +
        "ties(appointmentIds[0], \'Subject;Location;Start;End;Description;ResourceId\', OnG" +
        "etAppointmentProps);\r\n            } else\r\n                OnGetAppointmentProps(" +
        "null);\r\n        }\r\n        function OnGetAppointmentProps(values) {\r\n           " +
        " var subj = _aspxGetElementById(\'aptsubj\');\r\n            var loc = _aspxGetEleme" +
        "ntById(\'aptloc\');\r\n            var start = _aspxGetElementById(\'aptstart\');\r\n   " +
        "         var end = _aspxGetElementById(\'aptend\');\r\n            var resource = _a" +
        "spxGetElementById(\'aptres\');\r\n            var description = _aspxGetElementById(" +
        "\'aptdesc\');\r\n            if(values != null) {\r\n                subj.innerHTML = " +
        "values[0];\r\n                loc.innerHTML = values[1];\r\n                var form" +
        "atter = new ASPxDateFormatter();\r\n                formatter.SetFormatString(\"MM/" +
        "dd/yyyy HH:mm\");\r\n                start.innerHTML = formatter.Format(values[2]);" +
        "\r\n                end.innerHTML = formatter.Format(values[3]);\r\n                " +
        "resource.innerHTML = values[5];\r\n                description.innerHTML = values[" +
        "4].replace(/[\\n|\\r\\n]/g,\"<br />\");\r\n            } else {\r\n                var em" +
        "ptyStr = \'&nbsp\';\r\n                subj.innerHTML = emptyStr;\r\n                l" +
        "oc.innerHTML = emptyStr;\r\n                start.innerHTML = emptyStr;\r\n         " +
        "       end.innerHTML = emptyStr;\r\n                resource.innerHTML = emptyStr;" +
        "\r\n                description.innerHTML = emptyStr;\r\n            }\r\n        }\r\n " +
        "   // ]]> \r\n    </script>\r\n\t<style type=\"text/css\">\r\n\t\t#aptdesc {\r\n\t\t\tbackground" +
        "-color: #fff;\r\n\t\t\tborder: 1px solid #cccccc;\r\n\t\t\tpadding: 3px;\r\n\t\t}\r\n\t</style>\r\n" +
        "</asp:Content>\r\n<asp:Content ID=\"Content2\" ContentPlaceHolderID=\"MainContent\" ru" +
        "nat=\"server\">\r\n    <h2>Master Calendar- <asp:Label ID=\"timezone\" runat=\"server\" " +
        "/></h2>\r\n\t<p>\r\n    <dx:ASPxMenu ID=\"CalendarMenu\" ClientInstanceName=\"CalendarMe" +
        "nu\" runat=\"server\" EncodeHtml=\"False\">\r\n    </dx:ASPxMenu>\r\n\t</p>\r\n    \r\n    <dx" +
        ":ASPxTextBox ID=\"txtResourceID\" runat=\"server\" Visible=\"false\">\r\n    </dx:ASPxTe" +
        "xtBox>\r\n    <dx:ASPxScheduler ID=\"ASPxScheduler1\" runat=\"server\" ActiveViewType=" +
        "\"Timeline\"\r\n        ClientIDMode=\"AutoID\" AppointmentDataSourceID=\"AppointmentsD" +
        "ataSource\"\r\n        ResourceDataSourceID=\"ResourceDataSource\" >\r\n        <Storag" +
        "e>\r\n            <Appointments>\r\n                <Mappings AllDay=\"SiteVisitAppoi" +
        "ntment.AppointmentAllDay\" AppointmentId=\"SiteVisitAppointment.SiteVisitAppointme" +
        "ntID\" \r\n                    Label=\"SiteVisitAppointment.Label\" Location=\"SiteVis" +
        "itAppointment.AppointmentLocation\" Status=\"SiteVisitAppointment.Status\" \r\n      " +
        "              Subject=\"SiteVisitAppointment.Subject\" Description=\"SiteVisitAppoi" +
        "ntment.Description\" \r\n                    Start=\"SiteVisitAppointment.Appointmen" +
        "tStartDate\" End=\"SiteVisitAppointment.AppointmentEndDate\"  \r\n                   " +
        " RecurrenceInfo=\"SiteVisitAppointment.RecurrenceInfo\" ReminderInfo=\"SiteVisitApp" +
        "ointment.ReminderInfo\" \r\n                    ResourceId=\"SiteVisitAppointment.Re" +
        "sourceID\"   \r\n                    Type=\"SiteVisitAppointment.Type\" />\r\n         " +
        "   </Appointments>\r\n            <Resources>\r\n                <Mappings Caption=\"" +
        "ResourceName\" ResourceId=\"ResourceID\" />\r\n            </Resources>\r\n        </St" +
        "orage>\r\n        <Views>\r\n\t\t\t<DayView ResourcesPerPage=\"2\">\r\n                <Tim" +
        "eRulers>\r\n                    <dx:TimeRuler />\r\n                </TimeRulers>\r\n " +
        "               <DayViewStyles ScrollAreaHeight=\"200px\" />\r\n            </DayView" +
        ">\r\n            <WorkWeekView ResourcesPerPage=\"2\">\r\n                <TimeRulers>" +
        "\r\n                    <dx:TimeRuler />\r\n                </TimeRulers>\r\n         " +
        "       <WorkWeekViewStyles ScrollAreaHeight=\"200px\" />\r\n            </WorkWeekVi" +
        "ew>\r\n            <WeekView ResourcesPerPage=\"2\">\r\n                <WeekViewStyle" +
        "s>\r\n                    <DateCellBody Height=\"50px\" />\r\n                </WeekVi" +
        "ewStyles>\r\n            </WeekView>\r\n            <MonthView ResourcesPerPage=\"2\">" +
        "\r\n                <MonthViewStyles>\r\n                    <DateCellBody Height=\"5" +
        "0px\" />\r\n                </MonthViewStyles>\r\n            </MonthView>\r\n         " +
        "   <TimelineView ResourcesPerPage=\"2\">\r\n                <TimelineViewStyles>\r\n  " +
        "                  <TimelineCellBody Height=\"250px\" />\r\n                </Timelin" +
        "eViewStyles>\r\n            </TimelineView>\r\n        </Views>\r\n\t\t<OptionsCustomiza" +
        "tion AllowAppointmentCopy=\"None\" AllowAppointmentCreate=\"None\" AllowAppointmentD" +
        "elete=\"None\" AllowAppointmentDrag=\"None\" AllowAppointmentEdit=\"None\" AllowDispla" +
        "yAppointmentForm=\"Never\" />\r\n\t\t<ClientSideEvents AppointmentsSelectionChanged=\"f" +
        "unction(s, e) { OnAppointmentsSelectionChanged(s, e.appointmentIds); }\" />\r\n    " +
        "</dx:ASPxScheduler>\r\n    <asp:ObjectDataSource ID=\"ResourceDataSource\" runat=\"se" +
        "rver\" \r\n        SelectMethod=\"GetResources\" TypeName=\"OnSite.WebUI.Classes.Membe" +
        "rshipHelper\">\r\n    </asp:ObjectDataSource>\r\n    <asp:EntityDataSource ID=\"Appoin" +
        "tmentsDataSource\" runat=\"server\" \r\n        ConnectionString=\"name=SiteVisitDataE" +
        "ntities\" DefaultContainerName=\"SiteVisitDataEntities\" \r\n        EnableFlattening" +
        "=\"False\" \r\n        EntitySetName=\"");

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Appointments\" Include=\"");

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(",SiteVisitAppointment\" Where=\"");

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(reportViewerFilterExpression));

        
        #line default
        #line hidden
        
        #line 146 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\">\r\n        ");

        
        #line default
        #line hidden
        
        #line 147 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(whereParameters));

        
        #line default
        #line hidden
        
        #line 147 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\r\n    </asp:EntityDataSource> \r\n\t<br />\r\n    <table cellpadding=\"0\" cellspacing=\"" +
        "0\" width=\"100%\">\r\n        <tr valign=\"top\">\r\n            <td>\r\n            </td>" +
        "\r\n            <td style=\"width: 6px\">\r\n                &nbsp;\r\n            </td>" +
        "\r\n            <td>\r\n                <dx:ASPxRoundPanel ID=\"pnlAptSelection\" runa" +
        "t=\"server\" Width=\"100%\" HeaderText=\"Appointment Details\">\r\n                    <" +
        "ContentPaddings Padding=\"0px\" />\r\n                    <PanelCollection>\r\n       " +
        "                 <dx:PanelContent runat=\"server\">\r\n                            <" +
        "div>\r\n                                <table cellpadding=\"3\" cellspacing=\"2\" sty" +
        "le=\"width: 100%\">\r\n                                    <tr>\r\n                   " +
        "                     <td style=\"width: 20%\">\r\n                                  " +
        "          Subject:\r\n                                        </td>\r\n             " +
        "                           <td style=\"width: 80%\">\r\n                            " +
        "                <div id=\"aptsubj\" />\r\n                                        </" +
        "td>\r\n                                    </tr>\r\n                                " +
        "    <tr>\r\n                                        <td>\r\n                        " +
        "                    Location:\r\n                                        </td>\r\n  " +
        "                                      <td>\r\n                                    " +
        "        <div id=\"aptloc\" />\r\n                                        </td>\r\n    " +
        "                                </tr>\r\n                                    <tr>\r" +
        "\n                                        <td>\r\n                                 " +
        "           Start time:\r\n                                        </td>\r\n         " +
        "                               <td>\r\n                                           " +
        " <div id=\"aptstart\" />\r\n                                        </td>\r\n         " +
        "                           </tr>\r\n                                    <tr>\r\n    " +
        "                                    <td>\r\n                                      " +
        "      End time:\r\n                                        </td>\r\n                " +
        "                        <td>\r\n                                            <div i" +
        "d=\"aptend\" />\r\n                                        </td>\r\n                  " +
        "                  </tr>\r\n                                    <tr>\r\n             " +
        "                           <td>\r\n                                            Res" +
        "ource:\r\n                                        </td>\r\n                         " +
        "               <td>\r\n                                            <div id=\"aptres" +
        "\" />\r\n                                        </td>\r\n                           " +
        "         </tr>\r\n                                    <tr>\r\n                      " +
        "                  <td colspan=\"2\">\r\n                                            " +
        "Description:\r\n                                        </td>\r\n                   " +
        "                 </tr>\r\n                                    <tr>\r\n              " +
        "                          <td colspan=\"2\">\r\n                                    " +
        "        <div id=\"aptdesc\" />\r\n                                        </td>\r\n   " +
        "                                 </tr>\r\n                                </table>" +
        "\r\n                            </div>\r\n                        </dx:PanelContent>" +
        "\r\n                    </PanelCollection>\r\n                </dx:ASPxRoundPanel>\r\n" +
        "            </td>\r\n        </tr>\r\n    </table>\r\n</asp:Content>\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 224 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"

    }  

	private string GenerateGridViewColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) {

        
        #line default
        #line hidden
        
        #line 230 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 230 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 230 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 230 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 230 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\"\r\n\t\t\t\t\t\t\t\t\t\t\tReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 231 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldTabIndex));

        
        #line default
        #line hidden
        
        #line 231 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\">\r\n\t\t\t\t\t\t\t\t\t\t</dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 233 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		}
		return "";
	}
	
	private string GenerateNavBarItems(IEnumerable<SiteVisitForm> forms)
	{
		var query = from f in forms
					where f.SiteVisitParentFormID != null
					select f;
		foreach(SiteVisitForm form in query) {
			string visible = form.SiteVisitParentFormID == null ? "True" : "False";

        
        #line default
        #line hidden
        
        #line 245 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\t\t\t\t                <dx:NavBarItem Text=\"");

        
        #line default
        #line hidden
        
        #line 245 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 245 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" Name=\"");

        
        #line default
        #line hidden
        
        #line 245 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 245 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" Image-Url=\"~/Images/application_form.png\">                        \r\n           " +
        "                     </dx:NavBarItem>\r\n");

        
        #line default
        #line hidden
        
        #line 247 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		}
		return "";
	}

	private string GenerateUserControls(IEnumerable<SiteVisitForm> forms)
	{
		foreach(SiteVisitForm form in forms) {
			string visible = form.SiteVisitParentFormID == null ? "True" : "False";

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\t\t\t\t\t\t<uc:");

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" ID=\"uc");

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" runat=\"server\" Visible=\"");

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(visible));

        
        #line default
        #line hidden
        
        #line 256 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\" />\r\n");

        
        #line default
        #line hidden
        
        #line 257 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		}
		return "";
	}

    void GenerateCodeFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		string siteVisitID = sitevisit.SiteVisitID.ToString();
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 269 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;
using DevExpress.Web.ASPxClasses;
using XtraScheduler = DevExpress.XtraScheduler;
using DevExpress.Web.ASPxScheduler;
using System.Configuration;
using OnSite.WebUI.ClientCode.Models;
using OnSite.WebUI.Models;

namespace OnSite.WebUI.ClientCode.Reports
{
    public partial class Master");

        
        #line default
        #line hidden
        
        #line 287 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 287 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Schedule : System.Web.UI.Page\r\n    {\r\n        private int lastInsertedAppointment" +
        "Id;\r\n\r\n        SiteVisitDataEntities dataCtx = new SiteVisitDataEntities();\r\n\r\n " +
        "       protected void Page_Load(object sender, EventArgs e)\r\n        {\r\n        " +
        "    ASPxScheduler1.AppointmentRowInserted += new ASPxSchedulerDataInsertedEventH" +
        "andler(ASPxScheduler1_AppointmentRowInserted);\r\n            ASPxScheduler1.Appoi" +
        "ntmentRowInserting += new ASPxSchedulerDataInsertingEventHandler(ASPxScheduler1_" +
        "AppointmentRowInserting);\r\n            ASPxScheduler1.AppointmentRowUpdating += " +
        "new ASPxSchedulerDataUpdatingEventHandler(ASPxScheduler1_AppointmentRowUpdating)" +
        ";\r\n            ASPxScheduler1.AppointmentsInserted += new XtraScheduler.Persiste" +
        "ntObjectsEventHandler(ASPxScheduler1_AppointmentsInserted);\r\n            Appoint" +
        "mentsDataSource.Inserted += new EventHandler<EntityDataSourceChangedEventArgs>(A" +
        "ppointmentsDataSource_Inserted);\r\n\r\n            if (!IsPostBack)\r\n\t\t\t{\r\n\t\t\t\tSetC" +
        "alendarLinks();\r\n                txtResourceID.Text = Membership.GetUser().UserN" +
        "ame;\r\n\t\t\t\ttimezone.Text = ConfigurationManager.AppSettings[\"ICalTimeZone\"].ToStr" +
        "ing();\r\n\t\t\t}\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowI" +
        "nserted(object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertedEve" +
        "ntArgs e)\r\n        {\r\n            e.KeyFieldValue = this.lastInsertedAppointment" +
        "Id;\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowInserting(" +
        "object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertingEventArgs " +
        "e)\r\n        {\r\n            e.NewValues.Remove(\"SiteVisitAppointmentID\");\r\n      " +
        "      e.NewValues[\"SiteVisitID\"] = ");

        
        #line default
        #line hidden
        
        #line 317 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(siteVisitID));

        
        #line default
        #line hidden
        
        #line 317 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(";\r\n            if (e.NewValues[\"CreateDate\"] == null)\r\n                e.NewValue" +
        "s[\"CreateDate\"] = DateTime.Now;\r\n            e.NewValues[\"LastModifiedDate\"] = D" +
        "ateTime.Now;\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowU" +
        "pdating(object sender, ASPxSchedulerDataUpdatingEventArgs e)\r\n        {\r\n       " +
        "     e.NewValues[\"LastModifiedDate\"] = DateTime.Now;\r\n        }\r\n\r\n        prote" +
        "cted void ASPxScheduler1_AppointmentsInserted(object sender, DevExpress.XtraSche" +
        "duler.PersistentObjectsEventArgs e)\r\n        {\r\n            int count = e.Object" +
        "s.Count;\r\n            System.Diagnostics.Debug.Assert(count == 1);\r\n            " +
        "XtraScheduler.Appointment apt = (XtraScheduler.Appointment)e.Objects[0];\r\n      " +
        "      ASPxSchedulerStorage storage = (ASPxSchedulerStorage)sender;\r\n            " +
        "storage.SetAppointmentId(apt, this.lastInsertedAppointmentId);\r\n        }\r\n     " +
        "   protected void AppointmentsDataSource_Inserted(object sender, EntityDataSourc" +
        "eChangedEventArgs e)\r\n        {\r\n            SiteVisitAppointment apt = e.Entity" +
        " as SiteVisitAppointment;\r\n            if (apt == null)\r\n                return;" +
        "\r\n            this.lastInsertedAppointmentId = apt.SiteVisitAppointmentID;\r\n    " +
        "    }\r\n\r\n        protected void SetCalendarLinks()\r\n        {\r\n            Guid " +
        "onSiteUserGUID = (Guid)Membership.GetUser().ProviderUserKey;\r\n\r\n            stri" +
        "ng rootURL = Request.Url.AbsoluteUri.Replace(Request.Url.AbsolutePath, string.Em" +
        "pty);\r\n            rootURL = rootURL.Replace(\"http://\", string.Empty);\r\n\t\t\tstrin" +
        "g q = CadmusUtility.Encoding.Base64Encode(\"&SID=");

        
        #line default
        #line hidden
        
        #line 350 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(siteVisitID));

        
        #line default
        #line hidden
        
        #line 350 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("&UID=\" + onSiteUserGUID);\r\n            \r\n\t\t\tstring ICSNavigateUrl =  \"http://\" + " +
        "rootURL + ResolveUrl(\"~/WebServices/");

        
        #line default
        #line hidden
        
        #line 352 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 352 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Calendar.aspx?q=\" + q);\r\n            string OutlookNavigateUrl = \"webcal://\" + ro" +
        "otURL + ResolveUrl(\"~/WebServices/");

        
        #line default
        #line hidden
        
        #line 353 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 353 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(@"Calendar.aspx?q="" + q);

            CalendarMenu.Items.Add(""Open in Outlook"", ""Outlook"", ""~/Images/Outlook-icon.gif"", OutlookNavigateUrl, """");
            CalendarMenu.Items.Add(""Export to ICS"", ""ICS"", ""~/Images/ics_icon.gif"", ICSNavigateUrl, """");
        }
    }
}
");

        
        #line default
        #line hidden
        
        #line 360 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"

    }

	private string GenerateSummaryExpression(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 366 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + contact.");

        
        #line default
        #line hidden
        
        #line 366 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 366 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \" \"");

        
        #line default
        #line hidden
        
        #line 366 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		}
		return "";
	}

	private string GenerateLocationExpression(SiteVisitForm form)
	{
		var addressField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Address")
							select f).FirstOrDefault();
		var cityField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("City")
							select f).FirstOrDefault();
		var stateField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("State")
							select f).FirstOrDefault();
		var zipField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Zip") || f.FieldName.EndsWith("ZipCode")
							select f).FirstOrDefault();
		

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("contact.");

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressField.FieldName));

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cityField.FieldName));

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \", \" + contact.");

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stateField.FieldName));

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(zipField.FieldName));

        
        #line default
        #line hidden
        
        #line 386 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		return "";
	}

	private string GenerateDescriptionExpression(SiteVisitForm form)
	{
		var addressField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Address")
							select f).FirstOrDefault();
		var cityField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("City")
							select f).FirstOrDefault();
		var stateField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("State")
							select f).FirstOrDefault();
		var zipField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Zip") || f.FieldName.EndsWith("ZipCode")
							select f).FirstOrDefault();
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("PhoneNumber") || f.FieldName.EndsWith("Phone")
							select f);
		var summaryFields = SiteVisitDBHelper.GetSiteVisitSummaryFields(form);

		
		string summaryExpression = "";
		foreach (SiteVisitFormField phoneField in summaryFields)
		{
			summaryExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}

		string phoneExpression = "";
		foreach (SiteVisitFormField phoneField in phoneFields)
		{
			phoneExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}
		

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(summaryExpression));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneExpression));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("\"Address:\\n\" + contact.");

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressField.FieldName));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \"\\n\" + contact.");

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cityField.FieldName));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \", \" + contact.");

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stateField.FieldName));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(zipField.FieldName));

        
        #line default
        #line hidden
        
        #line 422 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
 
		return "";
	}

	void GenerateDesignerFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
	{
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 432 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.ClientCode.Reports {
    
    
    public partial class Master");

        
        #line default
        #line hidden
        
        #line 445 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 445 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"
this.Write("Schedule {\r\n\r\n        /// <summary>\r\n        /// CalendarMenu control.\r\n        /" +
        "// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n       " +
        " /// To modify move field declaration from designer file to code-behind file.\r\n " +
        "       /// </remarks>\r\n        protected global::DevExpress.Web.ASPxMenu.ASPxMen" +
        "u CalendarMenu;\r\n        \r\n        /// <summary>\r\n        /// txtResourceID cont" +
        "rol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated " +
        "field.\r\n        /// To modify move field declaration from designer file to code-" +
        "behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.A" +
        "SPxEditors.ASPxTextBox txtResourceID;\r\n        \r\n\t\t/// <summary>\r\n        /// ti" +
        "mezone control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto" +
        "-generated field.\r\n        /// To modify move field declaration from designer fi" +
        "le to code-behind file.\r\n        /// </remarks>\r\n        protected global::Syste" +
        "m.Web.UI.WebControls.Label timezone;\r\n\r\n        /// <summary>\r\n        /// ASPxS" +
        "cheduler1 control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// A" +
        "uto-generated field.\r\n        /// To modify move field declaration from designer" +
        " file to code-behind file.\r\n        /// </remarks>\r\n        protected global::De" +
        "vExpress.Web.ASPxScheduler.ASPxScheduler ASPxScheduler1;\r\n        \r\n\t\t/// <summa" +
        "ry>\r\n        /// pnlAptSelection control.\r\n        /// </summary>\r\n        /// <" +
        "remarks>\r\n        /// Auto-generated field.\r\n        /// To modify move field de" +
        "claration from designer file to code-behind file.\r\n        /// </remarks>\r\n     " +
        "   protected global::DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel pnlAptSelectio" +
        "n;\r\n\r\n\t\t\r\n        /// <summary>\r\n        /// ResourceDataSource control.\r\n      " +
        "  /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n    " +
        "    /// To modify move field declaration from designer file to code-behind file." +
        "\r\n        /// </remarks>\r\n        protected global::System.Web.UI.WebControls.Ob" +
        "jectDataSource ResourceDataSource;\r\n        \r\n        /// <summary>\r\n        ///" +
        " AppointmentsDataSource control.\r\n        /// </summary>\r\n        /// <remarks>\r" +
        "\n        /// Auto-generated field.\r\n        /// To modify move field declaration" +
        " from designer file to code-behind file.\r\n        /// </remarks>\r\n        protec" +
        "ted global::System.Web.UI.WebControls.EntityDataSource AppointmentsDataSource;\r\n" +
        "\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 512 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\ReportMasterScheduleTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class ReportMasterScheduleTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
