// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class ResourceScheduleTemplate : ResourceScheduleTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 2 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"

    void GeneratePage(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("<%@ Page Title=\"");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisit.SiteVisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" Language=\"C#\" MasterPageFile=\"~/Site.master\" AutoEventWireup=\"true\" CodeBehind=" +
        "\"My");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("Schedule.aspx.cs\" Inherits=\"OnSite.WebUI.ClientCode.Scheduler.My");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("Schedule\" %>\r\n<%@ Register Assembly=\"DevExpress.Web.ASPxScheduler.v13.1, Version=" +
        "13.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a\"\r\n    Namespace=\"DevE" +
        "xpress.Web.ASPxScheduler\" TagPrefix=\"dxwschs\" %>\r\n<%@ Register assembly=\"DevExpr" +
        "ess.XtraScheduler.v13.1.Core, Version=13.1.4.0, Culture=neutral, PublicKeyToken=" +
        "b88d1754d700e49a\" namespace=\"DevExpress.XtraScheduler\" tagprefix=\"dx\" %>\r\n<asp:C" +
        "ontent ID=\"Content1\" ContentPlaceHolderID=\"HeadContent\" runat=\"server\">\r\n</asp:C" +
        "ontent>\r\n<asp:Content ID=\"Content2\" ContentPlaceHolderID=\"MainContent\" runat=\"se" +
        "rver\">\r\n    <h2>My Schedule - <asp:Label ID=\"timezone\" runat=\"server\" /></h2>\r\n\t" +
        "<p>\r\n    <dx:ASPxMenu ID=\"CalendarMenu\" ClientInstanceName=\"CalendarMenu\" runat=" +
        "\"server\" EncodeHtml=\"False\">\r\n    </dx:ASPxMenu>\r\n\t</p>\r\n    \r\n    <dx:ASPxTextB" +
        "ox ID=\"txtResourceID\" runat=\"server\" Visible=\"false\">\r\n    </dx:ASPxTextBox>\r\n  " +
        "  <dx:ASPxScheduler ID=\"ASPxScheduler1\" runat=\"server\" ActiveViewType=\"Month\"\r\n " +
        "       GroupType=\"Resource\"\r\n        ClientIDMode=\"AutoID\" AppointmentDataSource" +
        "ID=\"AppointmentsDataSource\"\r\n        ResourceDataSourceID=\"ResourceDataSource\" >" +
        "\r\n        <Storage>\r\n            <Appointments>\r\n                <Mappings AllDa" +
        "y=\"AppointmentAllDay\" AppointmentId=\"SiteVisitAppointmentID\" \r\n                 " +
        "   Label=\"Label\" Location=\"AppointmentLocation\" Status=\"Status\" \r\n              " +
        "      Subject=\"Subject\" Description=\"Description\" \r\n                    Start=\"A" +
        "ppointmentStartDate\" End=\"AppointmentEndDate\"  \r\n                    RecurrenceI" +
        "nfo=\"RecurrenceInfo\" ReminderInfo=\"ReminderInfo\" \r\n                    ResourceI" +
        "d=\"ResourceID\"   \r\n                    Type=\"Type\" />\r\n            </Appointment" +
        "s>\r\n            <Resources>\r\n                <Mappings Caption=\"ResourceName\" Re" +
        "sourceId=\"ResourceID\" />\r\n            </Resources>\r\n        </Storage>\r\n        " +
        "<Views>\r\n            <DayView TimeScale=\"60\">\r\n                <TimeRulers>\r\n   " +
        "                 <dx:TimeRuler></dx:TimeRuler>\r\n                </TimeRulers>\r\n " +
        "           </DayView>\r\n            <WorkWeekView TimeScale=\"60\">\r\n              " +
        "  <TimeRulers>\r\n                    <dx:TimeRuler></dx:TimeRuler>\r\n             " +
        "   </TimeRulers>\r\n            </WorkWeekView>\r\n        </Views>\r\n    </dx:ASPxSc" +
        "heduler>\r\n    <asp:ObjectDataSource ID=\"ResourceDataSource\" runat=\"server\" \r\n   " +
        "     SelectMethod=\"GetMyResource\" TypeName=\"OnSite.WebUI.Classes.MembershipHelpe" +
        "r\">\r\n    </asp:ObjectDataSource>\r\n    <asp:EntityDataSource ID=\"AppointmentsData" +
        "Source\" runat=\"server\" \r\n        ConnectionString=\"name=SiteVisitDataEntities\" D" +
        "efaultContainerName=\"SiteVisitDataEntities\" \r\n\t\tContextTypeName=\"OnSite.WebUI.Cl" +
        "ientCode.Models.SiteVisitDataEntities\"\r\n        EnableDelete=\"True\" EnableFlatte" +
        "ning=\"False\" EnableInsert=\"True\" \r\n        EnableUpdate=\"True\" EntitySetName=\"Si" +
        "teVisitAppointments\" \r\n        StoreOriginalValuesInViewState=\"False\" \r\n        " +
        "Where=\"it.ResourceID = @ResourceID\">\r\n        <WhereParameters>\r\n            <as" +
        "p:ControlParameter ControlID=\"txtResourceID\" Name=\"ResourceID\" DbType=\"String\"\r\n" +
        "                PropertyName=\"Text\" />\r\n        </WhereParameters>\r\n    </asp:En" +
        "tityDataSource> \r\n</asp:Content>\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 87 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"

    }  

	private string GenerateGridViewColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) {

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 93 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\"\r\n\t\t\t\t\t\t\t\t\t\t\tReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldTabIndex));

        
        #line default
        #line hidden
        
        #line 94 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\">\r\n\t\t\t\t\t\t\t\t\t\t</dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 96 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		}
		return "";
	}
	
	private string GenerateNavBarItems(IEnumerable<SiteVisitForm> forms)
	{
		var query = from f in forms
					where f.SiteVisitParentFormID != null
					select f;
		foreach(SiteVisitForm form in query) {
			string visible = form.SiteVisitParentFormID == null ? "True" : "False";

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\t\t\t\t                <dx:NavBarItem Text=\"");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.UIDisplayName));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" Name=\"");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" Image-Url=\"~/Images/application_form.png\">                        \r\n           " +
        "                     </dx:NavBarItem>\r\n");

        
        #line default
        #line hidden
        
        #line 110 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		}
		return "";
	}

	private string GenerateUserControls(IEnumerable<SiteVisitForm> forms)
	{
		foreach(SiteVisitForm form in forms) {
			string visible = form.SiteVisitParentFormID == null ? "True" : "False";

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\t\t\t\t\t\t<uc:");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" ID=\"uc");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(form.DBTableName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" runat=\"server\" Visible=\"");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(visible));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\" />\r\n");

        
        #line default
        #line hidden
        
        #line 120 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		}
		return "";
	}

    void GenerateCodeFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		string siteVisitID = sitevisit.SiteVisitID.ToString();
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 132 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;
using DevExpress.Web.ASPxClasses;
using XtraScheduler = DevExpress.XtraScheduler;
using DevExpress.Web.ASPxScheduler;
using System.Configuration;
using OnSite.WebUI.ClientCode.Models;
using OnSite.WebUI.Models;

namespace OnSite.WebUI.ClientCode.Scheduler
{
    public partial class My");

        
        #line default
        #line hidden
        
        #line 150 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 150 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("Schedule : System.Web.UI.Page\r\n    {\r\n        private int lastInsertedAppointment" +
        "Id;\r\n\r\n        SiteVisitDataEntities dataCtx = new SiteVisitDataEntities();\r\n\r\n " +
        "       protected void Page_Load(object sender, EventArgs e)\r\n        {\r\n        " +
        "    ASPxScheduler1.AppointmentRowInserted += new ASPxSchedulerDataInsertedEventH" +
        "andler(ASPxScheduler1_AppointmentRowInserted);\r\n            ASPxScheduler1.Appoi" +
        "ntmentRowInserting += new ASPxSchedulerDataInsertingEventHandler(ASPxScheduler1_" +
        "AppointmentRowInserting);\r\n            ASPxScheduler1.AppointmentRowUpdating += " +
        "new ASPxSchedulerDataUpdatingEventHandler(ASPxScheduler1_AppointmentRowUpdating)" +
        ";\r\n            ASPxScheduler1.AppointmentsInserted += new XtraScheduler.Persiste" +
        "ntObjectsEventHandler(ASPxScheduler1_AppointmentsInserted);\r\n            Appoint" +
        "mentsDataSource.Inserted += new EventHandler<EntityDataSourceChangedEventArgs>(A" +
        "ppointmentsDataSource_Inserted);\r\n\r\n            if (!IsPostBack)\r\n\t\t\t{\r\n\t\t\t\tSetC" +
        "alendarLinks();\r\n                txtResourceID.Text = Membership.GetUser().UserN" +
        "ame;\r\n\t\t\t\ttimezone.Text = ConfigurationManager.AppSettings[\"ICalTimeZone\"].ToStr" +
        "ing();\r\n\t\t\t}\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowI" +
        "nserted(object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertedEve" +
        "ntArgs e)\r\n        {\r\n            e.KeyFieldValue = this.lastInsertedAppointment" +
        "Id;\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowInserting(" +
        "object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertingEventArgs " +
        "e)\r\n        {\r\n            e.NewValues.Remove(\"SiteVisitAppointmentID\");\r\n      " +
        "      e.NewValues[\"SiteVisitID\"] = ");

        
        #line default
        #line hidden
        
        #line 180 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(siteVisitID));

        
        #line default
        #line hidden
        
        #line 180 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(";\r\n            if (e.NewValues[\"CreateDate\"] == null)\r\n                e.NewValue" +
        "s[\"CreateDate\"] = DateTime.Now;\r\n            e.NewValues[\"LastModifiedDate\"] = D" +
        "ateTime.Now;\r\n        }\r\n\r\n        protected void ASPxScheduler1_AppointmentRowU" +
        "pdating(object sender, ASPxSchedulerDataUpdatingEventArgs e)\r\n        {\r\n       " +
        "     e.NewValues[\"LastModifiedDate\"] = DateTime.Now;\r\n        }\r\n\r\n        prote" +
        "cted void ASPxScheduler1_AppointmentsInserted(object sender, DevExpress.XtraSche" +
        "duler.PersistentObjectsEventArgs e)\r\n        {\r\n            int count = e.Object" +
        "s.Count;\r\n            System.Diagnostics.Debug.Assert(count == 1);\r\n            " +
        "XtraScheduler.Appointment apt = (XtraScheduler.Appointment)e.Objects[0];\r\n      " +
        "      ASPxSchedulerStorage storage = (ASPxSchedulerStorage)sender;\r\n            " +
        "storage.SetAppointmentId(apt, this.lastInsertedAppointmentId);\r\n        }\r\n     " +
        "   protected void AppointmentsDataSource_Inserted(object sender, EntityDataSourc" +
        "eChangedEventArgs e)\r\n        {\r\n            SiteVisitAppointment apt = e.Entity" +
        " as SiteVisitAppointment;\r\n            if (apt == null)\r\n                return;" +
        "\r\n            this.lastInsertedAppointmentId = apt.SiteVisitAppointmentID;\r\n    " +
        "    }\r\n\r\n        protected void SetCalendarLinks()\r\n        {\r\n            Guid " +
        "resourceGUID = (Guid)Membership.GetUser().ProviderUserKey;\r\n            Guid onS" +
        "iteUserGUID = (Guid)Membership.GetUser().ProviderUserKey;\r\n\r\n            string " +
        "rootURL = Request.Url.AbsoluteUri.Replace(Request.Url.AbsolutePath, string.Empty" +
        ");\r\n            rootURL = rootURL.Replace(\"http://\", string.Empty);\r\n\t\t\tstring q" +
        " = CadmusUtility.Encoding.Base64Encode(\"RID=\" + resourceGUID + \"&SID=");

        
        #line default
        #line hidden
        
        #line 214 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(siteVisitID));

        
        #line default
        #line hidden
        
        #line 214 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("&UID=\" + onSiteUserGUID);\r\n            \r\n\t\t\tstring ICSNavigateUrl =  \"http://\" + " +
        "rootURL + ResolveUrl(\"~/WebServices/");

        
        #line default
        #line hidden
        
        #line 216 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 216 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("Calendar.aspx?q=\" + q);\r\n            string OutlookNavigateUrl = \"webcal://\" + ro" +
        "otURL + ResolveUrl(\"~/WebServices/");

        
        #line default
        #line hidden
        
        #line 217 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 217 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(@"Calendar.aspx?q="" + q);

            CalendarMenu.Items.Add(""Open in Outlook"", ""Outlook"", ""~/Images/Outlook-icon.gif"", OutlookNavigateUrl, """");
            CalendarMenu.Items.Add(""Export to ICS"", ""ICS"", ""~/Images/ics_icon.gif"", ICSNavigateUrl, """");
        }
    }
}
");

        
        #line default
        #line hidden
        
        #line 224 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"

    }

	private string GenerateSummaryExpression(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + contact.");

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \" \"");

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		}
		return "";
	}

	private string GenerateLocationExpression(SiteVisitForm form)
	{
		var addressField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Address")
							select f).FirstOrDefault();
		var cityField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("City")
							select f).FirstOrDefault();
		var stateField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("State")
							select f).FirstOrDefault();
		var zipField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Zip") || f.FieldName.EndsWith("ZipCode")
							select f).FirstOrDefault();
		

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("contact.");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressField.FieldName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cityField.FieldName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \", \" + contact.");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stateField.FieldName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(zipField.FieldName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		return "";
	}

	private string GenerateDescriptionExpression(SiteVisitForm form)
	{
		var addressField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Address")
							select f).FirstOrDefault();
		var cityField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("City")
							select f).FirstOrDefault();
		var stateField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("State")
							select f).FirstOrDefault();
		var zipField = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("Zip") || f.FieldName.EndsWith("ZipCode")
							select f).FirstOrDefault();
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.FieldName.EndsWith("PhoneNumber") || f.FieldName.EndsWith("Phone")
							select f);
		var summaryFields = SiteVisitDBHelper.GetSiteVisitSummaryFields(form);

		
		string summaryExpression = "";
		foreach (SiteVisitFormField phoneField in summaryFields)
		{
			summaryExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}

		string phoneExpression = "";
		foreach (SiteVisitFormField phoneField in phoneFields)
		{
			phoneExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}
		

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(summaryExpression));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneExpression));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("\"Address:\\n\" + contact.");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressField.FieldName));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \"\\n\" + contact.");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cityField.FieldName));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \", \" + contact.");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stateField.FieldName));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(" + \" \" + contact.");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(zipField.FieldName));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
 
		return "";
	}

	void GenerateDesignerFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
	{
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.ClientCode.Scheduler {
    
    
    public partial class My");

        
        #line default
        #line hidden
        
        #line 309 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 309 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"
this.Write("Schedule {\r\n\r\n        /// <summary>\r\n        /// CalendarMenu control.\r\n        /" +
        "// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n       " +
        " /// To modify move field declaration from designer file to code-behind file.\r\n " +
        "       /// </remarks>\r\n        protected global::DevExpress.Web.ASPxMenu.ASPxMen" +
        "u CalendarMenu;\r\n        \r\n        /// <summary>\r\n        /// txtResourceID cont" +
        "rol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated " +
        "field.\r\n        /// To modify move field declaration from designer file to code-" +
        "behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.A" +
        "SPxEditors.ASPxTextBox txtResourceID;\r\n        \r\n\t\t/// <summary>\r\n        /// ti" +
        "mezone control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto" +
        "-generated field.\r\n        /// To modify move field declaration from designer fi" +
        "le to code-behind file.\r\n        /// </remarks>\r\n        protected global::Syste" +
        "m.Web.UI.WebControls.Label timezone;\r\n\r\n        /// <summary>\r\n        /// ASPxS" +
        "cheduler1 control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// A" +
        "uto-generated field.\r\n        /// To modify move field declaration from designer" +
        " file to code-behind file.\r\n        /// </remarks>\r\n        protected global::De" +
        "vExpress.Web.ASPxScheduler.ASPxScheduler ASPxScheduler1;\r\n        \r\n        /// " +
        "<summary>\r\n        /// ResourceDataSource control.\r\n        /// </summary>\r\n    " +
        "    /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To modify move" +
        " field declaration from designer file to code-behind file.\r\n        /// </remark" +
        "s>\r\n        protected global::System.Web.UI.WebControls.ObjectDataSource Resourc" +
        "eDataSource;\r\n        \r\n        /// <summary>\r\n        /// AppointmentsDataSourc" +
        "e control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-gene" +
        "rated field.\r\n        /// To modify move field declaration from designer file to" +
        " code-behind file.\r\n        /// </remarks>\r\n        protected global::System.Web" +
        ".UI.WebControls.EntityDataSource AppointmentsDataSource;\r\n\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 366 "C:\Users\ryan.kilkenny\Documents\Workspace\On-Site\Admin\OnSite.TemplateWizard\T4\ResourceScheduleTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ResourceScheduleTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
