// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnSite.TemplateWizard.Classes
{
    using System;
    using System.Data;
    using System.Data.Objects;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    using System.Data.Objects.DataClasses;
    using System.Text.RegularExpressions;
    using System.Xml;
    using System.Xml.Linq;
    using System.Text;
    using OnSite.TemplateWizard.Classes;
    using OnSite.TemplateWizard.Models;
    using System.Data.EntityClient;
    
    
    #line 1 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class SchedulerEditTemplate : SchedulerEditTemplateBase
    {
        public virtual string TransformText()
        {
            
            #line 2 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"

switch (OutputType) {
	case FileType.Page:
		GeneratePage(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Code:
		GenerateCodeFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	case FileType.Designer:
		GenerateDesignerFile(SiteVisit, SiteVisit.SiteVisitForms);
		break;
	default:
		break;
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 16 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"

    void GeneratePage(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 23 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("<%@ Page Title=\"");

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisit.SiteVisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\" Language=\"C#\" MasterPageFile=\"~/Fullscreen.master\" AutoEventWireup=\"true\" CodeB" +
        "ehind=\"");

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Edit.aspx.cs\" Inherits=\"OnSite.WebUI.Scheduler.");

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Edit\" %>\r\n<%@ Register Assembly=\"DevExpress.Web.ASPxScheduler.v12.1, Version=12.1" +
        ".4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a\"\r\n    Namespace=\"DevExpre" +
        "ss.Web.ASPxScheduler\" TagPrefix=\"dxwschs\" %>\r\n<%@ Register assembly=\"DevExpress." +
        "XtraScheduler.v12.1.Core, Version=12.1.4.0, Culture=neutral, PublicKeyToken=b88d" +
        "1754d700e49a\" namespace=\"DevExpress.XtraScheduler\" tagprefix=\"dx\" %>\r\n<%@ Regist" +
        "er src=\"~/UserControls/FormControls/ZipCode.ascx\" tagname=\"ZipCode\" tagprefix=\"u" +
        "c\" %>\r\n<%@ Register src=\"~/UserControls/FormControls/PhoneNumber.ascx\" tagname=\"" +
        "PhoneNumber\" tagprefix=\"uc\" %>\r\n<asp:Content ID=\"Content1\" ContentPlaceHolderID=" +
        "\"HeadContent\" runat=\"server\">\r\n    <script type=\"text/javascript\" src=\"https://m" +
        "aps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyDg2r9hOucSc8Whgr-4-bfvbXBv" +
        "zSEIAR0\"></script>\r\n    <script type=\"text/javascript\">\r\n        var map;\r\n     " +
        "   var markersArray = [];\r\n\t\tvar infowindowsArray = [];\r\n        var IsMapUpatin" +
        "g = false;\r\n\t\tvar lastSelectedVisibleIndex = -1;\r\n\r\n        function initialize(" +
        ") {\r\n            var myLatlng = new google.maps.LatLng(45.5236, -122.6750);  \r\n " +
        "           var myOptions = {\r\n                zoom: 12,\r\n                center:" +
        " myLatlng,\r\n                mapTypeId: google.maps.MapTypeId.ROADMAP\r\n          " +
        "  };\r\n            map = new google.maps.Map(document.getElementById(\'map_canvas\'" +
        "),\r\n            myOptions);\r\n            UpdateMap();\r\n        }\r\n        //Sinc" +
        "e the GetPageRowValues function causes a Callback on the grid, the IsMapUpdating" +
        " var keeps us from updating the map in an infinite loop.\r\n        function Updat" +
        "eMap() {\r\n            if (!IsMapUpating) {\r\n                IsMapUpating = true;" +
        "\r\n                grid.GetPageRowValues(\'");

        
        #line default
        #line hidden
        
        #line 54 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 54 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";LocationLatitude;LocationLongitude;\', function (values) {\r\n                    v" +
        "ar bounds = new google.maps.LatLngBounds();\r\n                    deleteOverlays(" +
        ");\r\n                    for (var i = 0; i < values.length; i++) {\r\n\t\t\t\t\t\tif (val" +
        "ues[i][0])\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\taddMarker(i, values[i][0], values[i][1], values[i][2" +
        "]);\r\n\t\t\t\t\t\t\tbounds.extend(new google.maps.LatLng(values[i][1], values[i][2]));\r\n" +
        "\t\t\t\t\t\t}\r\n                    }\r\n                    map.fitBounds(bounds);\r\n    " +
        "                if (map.zoom > 12)\r\n                        map.setZoom(12);\r\n  " +
        "                  setTimeout(function () { IsMapUpating = false; }, 500);\r\n     " +
        "           });\r\n            }\r\n        }\r\n\r\n        function addMarker(index, id" +
        ", latitude, longitude) {\r\n\t\t\tvar contentString = \"\"; //\'<div><a href=\"../SiteVis" +
        "its/VSDSchedulingEdit.aspx?ID=\'+ id +\'\">Edit Site</a></div>\';\r\n\t\t\t//loop through" +
        " grid columns write content into info window\r\n\t\t\tvar row = grid.GetRow(index);\r\n" +
        "\r\n\t\t\tfor (var x = 3; x < grid.columns.length; x++)\r\n\t\t\t{\r\n\t\t\t\tif (grid.columns[x" +
        "].visible == true && x < row.cells.length && x < 8) //limit to 5 fields\r\n\t\t\t\t{\r\n" +
        "\t\t\t\t\tcontentString += \"<div><strong>\"+grid.columns[x].fieldName+\"</strong>: \" + " +
        "row.cells[x].innerHTML + \"</div>\"; //\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tvar infowindow = new goog" +
        "le.maps.InfoWindow({\r\n\t\t\t\tcontent: contentString\r\n\t\t\t});\r\n            var marker" +
        " = new google.maps.Marker({\r\n                position: new google.maps.LatLng(la" +
        "titude, longitude),\r\n                map: map,\r\n                title: \'Site\'\r\n " +
        "           });\r\n            markersArray.push(marker);\r\n\t\t\tinfowindowsArray.push" +
        "(infowindow);\r\n\t\t\tgoogle.maps.event.addListener(marker, \'click\', function() {\r\n\t" +
        "\t\t  closeInfowindows();\r\n\t\t\t  infowindow.open(map,marker);\r\n\t\t\t  lastSelectedVis" +
        "ibleIndex = index;\r\n\t\t\t  cpSelectedSite.SetClientVisible(true);\r\n\t\t\t  splitter.G" +
        "etPaneByName(\"SelectedSitePane\").Expand();\r\n\t\t\t  grid.SelectRowOnPage(index);\r\n\t" +
        "\t\t  cpSelectedSite.PerformCallback(index);\r\n\t\t\t});\r\n        }\r\n\r\n        // Dele" +
        "tes all markers in the array by removing references to them\r\n        function de" +
        "leteOverlays() {\r\n            if (markersArray) {\r\n                for (i in mar" +
        "kersArray) {\r\n                    markersArray[i].setMap(null);\r\n               " +
        " }\r\n                markersArray.length = 0;\r\n            }\r\n        }\r\n\r\n\t\tfunc" +
        "tion closeInfowindows() {\r\n\t\t\tif (infowindowsArray) {\r\n                for (i in" +
        " infowindowsArray) {\r\n                    infowindowsArray[i].close();\r\n        " +
        "        }\r\n            }\r\n\t\t}\r\n\r\n        function OnGridRowClick(s, e) {\r\n\t\t\tclo" +
        "seInfowindows();\r\n\t\t\tlastSelectedVisibleIndex = e.visibleIndex;\r\n\t\t\tinfowindowsA" +
        "rray[e.visibleIndex].open(map,markersArray[e.visibleIndex])\r\n\t\t\tcpSelectedSite.S" +
        "etClientVisible(true);\r\n\t\t\tsplitter.GetPaneByName(\"SelectedSitePane\").Expand();\r" +
        "\n            cpSelectedSite.PerformCallback(e.visibleIndex);\t\r\n        }\r\n\r\n\t\tfu" +
        "nction OnSchedulerMenuItemClick(s, e) {\r\n\t\t\t//e.handled = true;\r\n\t\t\tvar errorMes" +
        "sage = \'Please select a site from the list.  Double-click the row you want to se" +
        "lect.\';\r\n\t\t\tif (lastSelectedVisibleIndex == -1)\r\n\t\t\t{\r\n\t\t\t\tswitch(e.itemName) {\r" +
        "\n\t\t\t\t\tcase SchedulerMenuItemId.NewRecurringAppointment:\r\n\t\t\t\t\tcase SchedulerMenu" +
        "ItemId.NewAllDayEvent:\r\n\t\t\t\t\tcase SchedulerMenuItemId.NewRecurringEvent:\r\n\t\t\t\t\tc" +
        "ase SchedulerMenuItemId.OpenAppointment:\r\n\t\t\t\t\tcase SchedulerMenuItemId.EditSeri" +
        "es:\r\n\t\t\t\t\tcase SchedulerMenuItemId.NewAppointment:\r\n\t\t\t\t\t\te.handled = true;\r\n\t\t\t" +
        "\t\t\talert(errorMessage);\r\n\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t//case SchedulerMenuItemId.DeleteApp" +
        "ointment:\r\n\t\t\t\t\t\t//e.handled = false;\r\n\t\t\t\t\t\t//break;\r\n\t\t\t\t\tdefault:\r\n\t\t\t\t\t\te.ha" +
        "ndled = false;    \r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t}\r\n\t\tfunction OnSiteMenuItemClick(s,e){\r\n\t\t\tc" +
        "pSelectedSite.PerformCallback(\'save\');\r\n\t\t}\r\n\r\n\t\tfunction OnSchedulerEndCallback" +
        "(s,e) {\r\n\t\t\tif (lastSelectedVisibleIndex > -1)\r\n\t\t\t\tcpSelectedSite.PerformCallba" +
        "ck(lastSelectedVisibleIndex);\r\n\t\t}\r\n\r\n        google.maps.event.addDomListener(w" +
        "indow, \'load\', initialize);\r\n    </script>\r\n    <style type=\"text/css\">\r\n      #" +
        "map_canvas {\r\n\t\theight: 100%;\r\n\t\twidth: 100%;\r\n\t  }\r\n    </style>\r\n</asp:Content" +
        ">\r\n<asp:Content ID=\"Content2\" ContentPlaceHolderID=\"MainContent\" runat=\"server\">" +
        "\r\n    <dx:ASPxSplitter ID=\"ASPxSplitter1\" runat=\"server\" EnableTheming=\"True\" Fu" +
        "llscreenMode=\"True\" ClientInstanceName=\"splitter\"\r\n        Theme=\"DevEx\" ShowCol" +
        "lapseBackwardButton=\"True\"\r\n        ShowCollapseForwardButton=\"True\">\r\n        <" +
        "Panes>\r\n            <dx:SplitterPane Size=\"30%\">\r\n                <Panes>\r\n     " +
        "               <dx:SplitterPane Name=\"MapPane\">\r\n                        <Conten" +
        "tCollection>\r\n                            <dx:SplitterContentControl>\r\n         " +
        "                       <div id=\"map_canvas\"></div>\r\n                            " +
        "</dx:SplitterContentControl>\r\n                        </ContentCollection>\r\n    " +
        "                </dx:SplitterPane>\r\n                    <dx:SplitterPane Name=\"S" +
        "itesListPane\" ScrollBars=\"Auto\">\r\n                        <ContentCollection>\r\n " +
        "                           <dx:SplitterContentControl>\r\n\t\t\t\t\t\t\t\t<h3>Site List (c" +
        "lick to select)</h3>\r\n\t\t\t\t\t\t\t\t<dx:ASPxButton ID=\"btnRefresh\" runat=\"server\" Auto" +
        "Postback=\"false\" Text=\"Refresh\">\r\n\t\t\t\t\t\t\t\t\t<ClientSideEvents Click=\"function(s,e" +
        "){grid.PerformCallback();}\" />\r\n\t\t\t\t\t\t\t\t</dx:ASPxButton>\r\n\t\t\t\t\t\t\t\t<p>\r\n\t\t\t\t\t\t\t\t<" +
        "dx:ASPxGridView ID=\"ASPxGridView1\" runat=\"server\" AutoGenerateColumns=\"False\" Cl" +
        "ientInstanceName=\"grid\" KeyFieldName=\"");

        
        #line default
        #line hidden
        
        #line 195 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 195 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\">\r\n\t\t\t\t\t\t\t\t\t<Columns>\r\n\t\t\t\t\t\t\t\t\t\t<dx:GridViewCommandColumn VisibleIndex=\"0\">\r\n\t\t" +
        "\t\t\t\t\t\t\t\t\t<ClearFilterButton Visible=\"True\">\r\n\t\t\t\t\t\t\t\t\t\t\t</ClearFilterButton>\r\n\t\t" +
        "\t\t\t\t\t\t\t\t</dx:GridViewCommandColumn>\r\n\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldN" +
        "ame=\"");

        
        #line default
        #line hidden
        
        #line 201 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 201 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@""" 
											ReadOnly=""True"" VisibleIndex=""0"" Visible=""False"">
										</dx:GridViewDataTextColumn>
										<dx:GridViewDataComboBoxColumn FieldName=""DispositionID"" Caption=""Disposition"" ReadOnly=""True"" VisibleIndex=""0"" Visible=""true"">
											<PropertiesComboBox DataSourceID=""DispositionsDataSource"" ValueField=""DispositionID"" IncrementalFilteringMode=""StartsWith"" TextField=""DispositionName"" ValueType=""System.Int32"" DropDownStyle=""DropDown"" />
										</dx:GridViewDataComboBoxColumn>
");

        
        #line default
        #line hidden
        
        #line 207 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateGridViewColumns(parentForm)));

        
        #line default
        #line hidden
        
        #line 207 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"LocationLatitude\" \r\n\t\t\t\t\t\t\t\t\t\t\t" +
        "ReadOnly=\"True\" VisibleIndex=\"0\" Visible=\"False\">\r\n\t\t\t\t\t\t\t\t\t\t</dx:GridViewDataTe" +
        "xtColumn>\r\n\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"LocationLongitude\" \r\n" +
        "\t\t\t\t\t\t\t\t\t\t\tReadOnly=\"True\" VisibleIndex=\"0\" Visible=\"False\">\r\n\t\t\t\t\t\t\t\t\t\t</dx:Gri" +
        "dViewDataTextColumn>\r\n\t\t\t\t\t\t\t\t\t</Columns>\r\n\t\t\t\t\t\t\t\t\t<Settings ShowFilterRow=\"Tru" +
        "e\" ShowHeaderFilterButton=\"true\" />\r\n                                    <Settin" +
        "gsBehavior AllowSelectByRowClick=\"true\" AllowSelectSingleRowOnly=\"true\" />\r\n    " +
        "                                <ClientSideEvents EndCallback=\"function(s,e){Upd" +
        "ateMap();}\" RowClick=\"OnGridRowClick\" />\r\n\t\t\t\t\t\t\t\t</dx:ASPxGridView>\r\n\t\t\t\t\t\t\t\t<a" +
        "sp:EntityDataSource ID=\"DispositionsDataSource\" runat=\"server\" \r\n\t\t\t\t\t\t\t\t\tConnec" +
        "tionString=\"name=SiteVisitDataEntities\" DefaultContainerName=\"SiteVisitDataEntit" +
        "ies\" \r\n\t\t\t\t\t\t\t\t\tEnableFlattening=\"False\" EntitySetName=\"Dispositions\">\r\n\t\t\t\t\t\t\t\t" +
        "</asp:EntityDataSource> \r\n\t\t\t\t\t\t\t\t</p>\r\n                            </dx:Splitte" +
        "rContentControl>\r\n                        </ContentCollection>                  " +
        "  \r\n                    </dx:SplitterPane>\r\n                </Panes>\r\n\t\t\t\t<Conte" +
        "ntCollection>\r\n\t\t\t\t\t<dx:SplitterContentControl runat=\"server\" SupportsDisabledAt" +
        "tribute=\"True\"></dx:SplitterContentControl>\r\n\t\t\t\t</ContentCollection>\r\n\t\t\t</dx:S" +
        "plitterPane>\r\n            <dx:SplitterPane Name=\"SchedulerPane\">\r\n              " +
        "  <Panes>\r\n                    <dx:SplitterPane ScrollBars=\"Auto\">\r\n            " +
        "        <ContentCollection>\r\n                        <dx:SplitterContentControl>" +
        "\r\n\t\t\t\t\t\t\t<h2>Current Schedule - <asp:Label ID=\"timezone\" runat=\"server\" /></h2>\r" +
        "\n                            <dxwschs:ASPxScheduler ID=\"ASPxScheduler1\" runat=\"s" +
        "erver\"  ActiveViewType=\"WorkWeek\"\r\n                                GroupType=\"Re" +
        "source\" EncodeHtml=\"False\"\r\n                                AppointmentDataSourc" +
        "eID=\"AppointmentsDataSource\" ClientIDMode=\"AutoID\" ResourceDataSourceID=\"Resourc" +
        "eDataSource\" >\r\n                                <Storage>\r\n                     " +
        "               <Appointments>\r\n                                        <Mappings" +
        " AllDay=\"AppointmentAllDay\" AppointmentId=\"SiteVisitAppointmentID\" \r\n           " +
        "                                 Label=\"Label\" Location=\"AppointmentLocation\" St" +
        "atus=\"Status\" \r\n                                            Subject=\"Subject\" De" +
        "scription=\"Description\" \r\n                                            Start=\"App" +
        "ointmentStartDate\" End=\"AppointmentEndDate\"  \r\n                                 " +
        "           RecurrenceInfo=\"RecurrenceInfo\" ReminderInfo=\"ReminderInfo\" \r\n       " +
        "                                     ResourceId=\"ResourceID\"   \r\n               " +
        "                             Type=\"Type\" />\r\n                                   " +
        " </Appointments>\r\n                                    <Resources>\r\n             " +
        "                           <Mappings Caption=\"ResourceName\" ResourceId=\"Resource" +
        "ID\" />\r\n                                    </Resources>\r\n                      " +
        "          </Storage>\r\n                                <Views>\r\n                 " +
        "                   <DayView TimeScale=\"60\">\r\n                                   " +
        "     <TimeRulers>\r\n                                            <dx:TimeRuler></d" +
        "x:TimeRuler>\r\n                                        </TimeRulers>\r\n           " +
        "                         </DayView>\r\n                                    <WorkWe" +
        "ekView TimeScale=\"60\">\r\n                                        <TimeRulers>\r\n  " +
        "                                          <dx:TimeRuler></dx:TimeRuler>\r\n       " +
        "                                 </TimeRulers>\r\n                                " +
        "    </WorkWeekView>\r\n                                </Views>\r\n                 " +
        "               <ClientSideEvents MenuItemClicked=\"OnSchedulerMenuItemClick\" EndC" +
        "allback=\"OnSchedulerEndCallback\" />\r\n                            </dxwschs:ASPxS" +
        "cheduler>\r\n                            <asp:ObjectDataSource ID=\"ResourceDataSou" +
        "rce\" runat=\"server\" \r\n                                SelectMethod=\"GetResources" +
        "\" TypeName=\"OnSite.WebUI.Classes.MembershipHelper\">\r\n                           " +
        " </asp:ObjectDataSource>\r\n                            <asp:EntityDataSource ID=\"" +
        "AppointmentsDataSource\" runat=\"server\" \r\n                                Connect" +
        "ionString=\"name=SiteVisitDataEntities\" DefaultContainerName=\"SiteVisitDataEntiti" +
        "es\" \r\n                                EnableDelete=\"True\" EnableFlattening=\"Fals" +
        "e\" EnableInsert=\"True\" \r\n                                EnableUpdate=\"True\" Ent" +
        "itySetName=\"SiteVisitAppointments\" StoreOriginalValuesInViewState=\"false\">\r\n    " +
        "                        </asp:EntityDataSource>         \r\n                      " +
        "  </dx:SplitterContentControl>\r\n                    </ContentCollection>\r\n      " +
        "              </dx:SplitterPane>\r\n                    <dx:SplitterPane Size=\"30%" +
        "\" ScrollBars=\"Auto\" Name=\"SelectedSitePane\" Collapsed=\"true\">\r\n                 " +
        "       <ContentCollection>\r\n                            <dx:SplitterContentContr" +
        "ol>\r\n                                <dx:ASPxCallbackPanel ID=\"cpSelectedSite\" r" +
        "unat=\"server\" Width=\"100%\" ClientInstanceName=\"cpSelectedSite\" ClientVisible=\"fa" +
        "lse\">\r\n                                    <PanelCollection>\r\n                  " +
        "                      <dx:PanelContent>\r\n                                       " +
        "     <dx:ASPxHiddenField ID=\"hf\" runat=\"server\" ClientInstanceName=\"hf\">\r\n      " +
        "                                      </dx:ASPxHiddenField>\r\n\t\t\t\t\t\t\t\t\t\t\t<table>\r" +
        "\n\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:ASPxMenu ID=\"ASPxMenu1\" " +
        "runat=\"server\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<Items>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:MenuItem Text=\"Save" +
        " Changes\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</dx:MenuItem>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</Items>\r\n\t\t\t\t\t\t\t\t\t\t\t" +
        "\t\t\t\t<ClientSideEvents ItemClick=\"OnSiteMenuItemClick\" />\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</dx:ASP" +
        "xMenu>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Last modified: <dx:ASPxLabel ID=\"lb" +
        "lSavedDate\" runat=\"server\" Text=\"ASPxLabel\"></dx:ASPxLabel></td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<" +
        "td>Modified by: <dx:ASPxLabel ID=\"lblSavedBy\" runat=\"server\" Text=\"ASPxLabel\"></" +
        "dx:ASPxLabel></td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t</table>\r\n\t\t\t\t\t\t\t\t\t\t\t<div id=\"" +
        "SchedulerSelectedSite\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<table class=\"SelectedSiteTable\">\r\n\t\t\t\t\t\t\t\t" +
        "\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td valign=\"top\" class=\"SelectedSiteSummary\">\r\n\t\t\t\t\t\t\t\t" +
        "\t\t\t\t\t\t\t<fieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<legend>Summary</legend>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ta" +
        "ble>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Disposition:</td>\r\n\t\t\t\t\t\t\t\t\t\t" +
        "\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:ASPxComboBox ID=\"cbDisposition\" runat=\"serv" +
        "er\" ValueType=\"System.Int32\" Width=\"125px\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</dx:ASPxComboBo" +
        "x>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 317 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateSummaryLabels(parentForm)));

        
        #line default
        #line hidden
        
        #line 317 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"
																</table>
															</fieldset>
														</td>
														<td valign=""top"" class=""SelectedSiteAddress"">
															<fieldset>
																<legend>Address</legend>
																<table>
																	<tr>
																		<td>
																			Address:
																			<dx:ASPxTextBox ID=""tbAddress1"" runat=""server"" Width=""140px"">
                                                                            </dx:ASPxTextBox>
																			<dx:ASPxTextBox ID=""tbAddress2"" runat=""server"" Width=""140px"">
                                                                            </dx:ASPxTextBox>
																			City:
																			<dx:ASPxTextBox ID=""tbCity"" runat=""server"" Width=""140px"">
                                                                            </dx:ASPxTextBox>
																			State:
																			<dx:ASPxTextBox ID=""tbState"" runat=""server"" Width=""140px"">
                                                                            </dx:ASPxTextBox>
																			Zip:
																			<uc:ZipCode ID=""tbZip"" runat=""server"" IsRequired=""False"" />
																		</td>
																	</tr>
																</table>
															</fieldset>
														</td>
														<td valign=""top"" class=""SelectedSitePhone"">
															<fieldset>
																<legend>Phone</legend>
																<table>
");

        
        #line default
        #line hidden
        
        #line 349 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratePhoneInputs(parentForm)));

        
        #line default
        #line hidden
        
        #line 349 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t" +
        "\t\t\t\t\t\t\t\t\t\t<td rowspan=\"2\" valign=\"top\" class=\"SelectedSiteAppointments\">\r\n\t\t\t\t\t\t" +
        "\t\t\t\t\t\t\t\t\t<fieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<legend>Appointments</legend>\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
        "\t\t\t\t<dx:ASPxGridView ID=\"gridAppointments\" runat=\"server\" Width=\"100%\" \r\n\t\t\t\t\t\t\t" +
        "\t\t\t\t\t\t\t\t\t\tAutoGenerateColumns=\"False\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<Columns>\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
        "\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"AppointmentStatus.AppointmentStatusN" +
        "ame\" Caption=\"Appointment Status\" VisibleIndex=\"1\"></dx:GridViewDataTextColumn>\r" +
        "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"SiteVisitAppointment.Re" +
        "sourceID\" VisibleIndex=\"2\"></dx:GridViewDataTextColumn>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t" +
        "\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"SiteVisitAppointment.Appointm" +
        "entStartDate\" VisibleIndex=\"7\"></dx:GridViewDataTextColumn>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<" +
        "dx:GridViewDataTextColumn FieldName=\"SiteVisitAppointment.AppointmentEndDate\" Vi" +
        "sibleIndex=\"8\"></dx:GridViewDataTextColumn>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</Columns>\r\n\t\t\t\t\t\t" +
        "\t\t\t\t\t\t\t\t\t\t</dx:ASPxGridView>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t" +
        "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" valign=\"top\"" +
        " class=\"SelectedSiteNotes\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<legend>" +
        "Notes</legend>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:ASPxMemo ID=\"SchedulerNotes\" runat=\"server\" " +
        "Height=\"100px\" Width=\"100%\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</dx:ASPxMemo>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</f" +
        "ieldset>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n       " +
        "                                     </div>\r\n                                   " +
        "     </dx:PanelContent>\r\n                                    </PanelCollection>\r" +
        "\n                                </dx:ASPxCallbackPanel>\r\n                      " +
        "      </dx:SplitterContentControl>\r\n                        </ContentCollection>" +
        "\r\n                    </dx:SplitterPane>\r\n                </Panes>\r\n            " +
        "</dx:SplitterPane>\r\n            \r\n        </Panes>\r\n    </dx:ASPxSplitter>\r\n</as" +
        "p:Content>\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 392 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"

    }  

	private string GenerateGridViewColumns(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSearchableFields(form)) {

        
        #line default
        #line hidden
        
        #line 398 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\t\t\t\t\t\t\t\t<dx:GridViewDataTextColumn FieldName=\"");

        
        #line default
        #line hidden
        
        #line 398 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 398 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\" Caption=\"");

        
        #line default
        #line hidden
        
        #line 398 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldLabel));

        
        #line default
        #line hidden
        
        #line 398 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"\r\n\t\t\t\t\t\t\t\t\t\t\tReadOnly=\"True\" VisibleIndex=\"");

        
        #line default
        #line hidden
        
        #line 399 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldTabIndex));

        
        #line default
        #line hidden
        
        #line 399 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\">\r\n\t\t\t\t\t\t\t\t\t\t</dx:GridViewDataTextColumn>\r\n");

        
        #line default
        #line hidden
        
        #line 401 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}

	private string GenerateSummaryLabels(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 409 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");

        
        #line default
        #line hidden
        
        #line 410 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(StringSanitizer.SanitizeForWeb(field.FieldLabel)));

        
        #line default
        #line hidden
        
        #line 410 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(":</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<dx:ASPxLabel ID=\"lbl");

        
        #line default
        #line hidden
        
        #line 412 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 412 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\" runat=\"server\" Text=\"\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</dx:ASPxLabel>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t" +
        "</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 416 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}
	

	private string GeneratePhoneInputs(SiteVisitForm form)
	{
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.ControlType.UITypeName == "PhoneNumber"
							select f);
		foreach (SiteVisitFormField field in phoneFields)
		{

        
        #line default
        #line hidden
        
        #line 429 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 431 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(StringSanitizer.SanitizeForWeb(field.FieldLabel)));

        
        #line default
        #line hidden
        
        #line 431 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<uc:PhoneNumber ID=\"uc");

        
        #line default
        #line hidden
        
        #line 432 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 432 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\" runat=\"server\" \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tVisible=\"True\" \r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tIsReq" +
        "uired=\"False\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</uc:");

        
        #line default
        #line hidden
        
        #line 435 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.ControlType.UITypeName));

        
        #line default
        #line hidden
        
        #line 435 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 438 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}
    void GenerateCodeFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
    {
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		string siteVisitID = sitevisit.SiteVisitID.ToString();
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 449 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;
using DevExpress.Web.ASPxClasses;
using XtraScheduler = DevExpress.XtraScheduler;
using DevExpress.Web.ASPxScheduler;
using System.Configuration;
using OnSite.WebUI.Models;

namespace OnSite.WebUI.Scheduler
{
    public partial class ");

        
        #line default
        #line hidden
        
        #line 466 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 466 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Edit : System.Web.UI.Page\r\n    {\r\n        private int lastInsertedAppointmentId;\r" +
        "\n\r\n        SiteVisitDataEntities dataCtx = new SiteVisitDataEntities();\r\n\r\n     " +
        "   protected void Page_Load(object sender, EventArgs e)\r\n        {\r\n            " +
        "ASPxScheduler1.AppointmentRowInserted +=new ASPxSchedulerDataInsertedEventHandle" +
        "r(ASPxScheduler1_AppointmentRowInserted);\r\n            ASPxScheduler1.Appointmen" +
        "tRowInserting +=new ASPxSchedulerDataInsertingEventHandler(ASPxScheduler1_Appoin" +
        "tmentRowInserting);\r\n            ASPxScheduler1.AppointmentRowUpdating += new AS" +
        "PxSchedulerDataUpdatingEventHandler(ASPxScheduler1_AppointmentRowUpdating);\r\n   " +
        "         ASPxScheduler1.AppointmentsInserted +=new XtraScheduler.PersistentObjec" +
        "tsEventHandler(ASPxScheduler1_AppointmentsInserted);\r\n            ASPxScheduler1" +
        ".AppointmentFormShowing += new AppointmentFormEventHandler(ASPxScheduler1_Appoin" +
        "tmentFormShowing);\r\n            cpSelectedSite.Callback += new CallbackEventHand" +
        "lerBase(cpSelectedSite_Callback);\r\n            AppointmentsDataSource.Inserted +" +
        "= new EventHandler<EntityDataSourceChangedEventArgs>(AppointmentsDataSource_Inse" +
        "rted);\r\n\t\t\tASPxGridView1_Bind();\r\n            if (!IsPostBack)\r\n\t\t\t{\r\n          " +
        "      ASPxGridView1.ExpandAll();\r\n\t\t\t\ttimezone.Text = ConfigurationManager.AppSe" +
        "ttings[\"ICalTimeZone\"].ToString();\r\n\t\t\t\tcbDisposition.DataSource = dataCtx.Dispo" +
        "sitions.OrderBy(d => d.DisplayOrder);\r\n\t\t\t\tcbDisposition.TextField = \"Dispositio" +
        "nName\";\r\n\t\t\t\tcbDisposition.ValueField = \"DispositionID\";\r\n\t\t\t\tcbDisposition.Data" +
        "Bind();\r\n\t\t\t}\r\n        }\r\n\r\n\t\tprotected void ASPxGridView1_Bind()\r\n\t\t{\r\n\t\t\tASPxG" +
        "ridView1.DataSource = (from i in dataCtx.");

        
        #line default
        #line hidden
        
        #line 495 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 495 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"
										where i.LocationLatitude != null
										select i);
			ASPxGridView1.DataBind();
		}

        protected void ASPxScheduler1_AppointmentFormShowing(object sender, AppointmentFormEventArgs e)
        {
            if (e.Action == SchedulerFormAction.Create)
            {
                if (hf[""");

        
        #line default
        #line hidden
        
        #line 505 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 505 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"] != null)\r\n                {\r\n                    int contactId = (int)hf[\"");

        
        #line default
        #line hidden
        
        #line 507 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 507 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"];\r\n                    var contact = (from d in dataCtx.");

        
        #line default
        #line hidden
        
        #line 508 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 508 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n                                   where d.");

        
        #line default
        #line hidden
        
        #line 509 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 509 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" == contactId\r\n                                    select d).FirstOrDefault();\r\n\r" +
        "\n                    e.Appointment.Subject = \"Site Visit: \"");

        
        #line default
        #line hidden
        
        #line 512 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateSummaryExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 512 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n                    e.Appointment.Location = ");

        
        #line default
        #line hidden
        
        #line 513 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateLocationExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 513 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n\t\t\t\t\te.Appointment.Description = ");

        
        #line default
        #line hidden
        
        #line 514 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateDescriptionExpression(parentForm, sitevisitName)));

        
        #line default
        #line hidden
        
        #line 514 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@";
                    e.Appointment.StatusId = 3;
                    e.Appointment.LabelId = 6;
                }
                else
                {
                    e.Cancel = true;
                }
            }
        }

        protected void cpSelectedSite_Callback(object sender, CallbackEventArgsBase e)
        {
			");

        
        #line default
        #line hidden
        
        #line 527 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 527 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" contact;\r\n\r\n\t\t\tif (e.Parameter == \"save\")\r\n\t\t\t{\r\n\t\t\t\tint id = (int)hf[\"");

        
        #line default
        #line hidden
        
        #line 531 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 531 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"];\r\n\t\t\t\tcontact = (from d in dataCtx.");

        
        #line default
        #line hidden
        
        #line 532 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 532 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\t\t\t\t   where d.");

        
        #line default
        #line hidden
        
        #line 533 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 533 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" == id\r\n\t\t\t\t\t\t\t   select d).FirstOrDefault();\r\n");

        
        #line default
        #line hidden
        
        #line 535 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateAddressSaveExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 535 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 536 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratePhoneSaveExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 536 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"
				contact.SchedulerNotes = SchedulerNotes.Text;
				contact.DispositionID = (int)cbDisposition.SelectedItem.Value;
				contact.ModifiedDate = DateTime.Now;
				contact.ModifiedUser = Membership.GetUser().UserName;
				dataCtx.SaveChanges();
			}
			else 
			{
			// Load
				int id = (int)ASPxGridView1.GetRowValues(int.Parse(e.Parameter), """);

        
        #line default
        #line hidden
        
        #line 546 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 546 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\");\r\n\t\t\t\tcontact = (from d in dataCtx.");

        
        #line default
        #line hidden
        
        #line 547 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 547 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\t\t\t\t   where d.");

        
        #line default
        #line hidden
        
        #line 548 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 548 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" == id\r\n\t\t\t\t\t\t\t   select d).FirstOrDefault();\r\n\t\t\t\thf[\"");

        
        #line default
        #line hidden
        
        #line 550 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 550 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"] = id;\r\n\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 552 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateSummaryLabelsExpressions(parentForm)));

        
        #line default
        #line hidden
        
        #line 552 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 553 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateAddressExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 553 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 554 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratePhoneExpression(parentForm)));

        
        #line default
        #line hidden
        
        #line 554 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\tcbDisposition.Items.FindByValue(contact.DispositionID).Selected = true;\r\n\t\t\t" +
        "lblSavedDate.Text = contact.ModifiedDate.ToString();\r\n\t\t\tlblSavedBy.Text = conta" +
        "ct.ModifiedUser;         \r\n\t\t\tgridAppointments.DataSource = dataCtx.");

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Appointments.Include(\"SiteVisitAppointment\").Include(\"AppointmentStatus\").Where(a" +
        " => a.");

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" == contact.");

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 558 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@").OrderBy(a => a.SiteVisitAppointment.AppointmentStartDate);
			gridAppointments.DataBind();
			SchedulerNotes.Text = contact.SchedulerNotes;
        }

        protected void ASPxScheduler1_AppointmentRowInserted(object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertedEventArgs e)
        {
            e.KeyFieldValue = this.lastInsertedAppointmentId;
        }

        protected void ASPxScheduler1_AppointmentRowInserting(object sender, DevExpress.Web.ASPxScheduler.ASPxSchedulerDataInsertingEventArgs e)
        {
            e.NewValues.Remove(""SiteVisitAppointmentID"");
            e.NewValues[""SiteVisitID""] = ");

        
        #line default
        #line hidden
        
        #line 571 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(siteVisitID));

        
        #line default
        #line hidden
        
        #line 571 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@";
            if (e.NewValues[""CreateDate""] == null)
                e.NewValues[""CreateDate""] = DateTime.Now;
            e.NewValues[""LastModifiedDate""] = DateTime.Now;
        }

        protected void ASPxScheduler1_AppointmentRowUpdating(object sender, ASPxSchedulerDataUpdatingEventArgs e)
        {
            e.NewValues[""LastModifiedDate""] = DateTime.Now;
        }

        protected void ASPxScheduler1_AppointmentsInserted(object sender, DevExpress.XtraScheduler.PersistentObjectsEventArgs e)
        {
            int count = e.Objects.Count;
            System.Diagnostics.Debug.Assert(count == 1);
            XtraScheduler.Appointment apt = (XtraScheduler.Appointment)e.Objects[0];
            ASPxSchedulerStorage storage = (ASPxSchedulerStorage)sender;
            storage.SetAppointmentId(apt, this.lastInsertedAppointmentId);
            if (hf[""");

        
        #line default
        #line hidden
        
        #line 589 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 589 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"] != null)\r\n            {\r\n                int contactId = (int)hf[\"");

        
        #line default
        #line hidden
        
        #line 591 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 591 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"];\r\n                var contactAppt = (from a in dataCtx.");

        
        #line default
        #line hidden
        
        #line 592 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 592 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"Appointments
                                   where a.SiteVisitAppointmentID == this.lastInsertedAppointmentId
                                   select a).FirstOrDefault();
                if (contactAppt == null)
                {
                    contactAppt = new ");

        
        #line default
        #line hidden
        
        #line 597 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 597 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Appointments();\r\n                    contactAppt.SiteVisitAppointmentID = this.la" +
        "stInsertedAppointmentId;\r\n                    contactAppt.");

        
        #line default
        #line hidden
        
        #line 599 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkey));

        
        #line default
        #line hidden
        
        #line 599 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = contactId;      \r\n\t\t\t\t\tcontactAppt.AppointmentStatusID = ");

        
        #line default
        #line hidden
        
        #line 600 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(SiteVisitDBHelper.GetDefaultAppointmentStatus()));

        
        #line default
        #line hidden
        
        #line 600 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@";
                    contactAppt.CreateDate = DateTime.Now;
                    contactAppt.CreateUser = Membership.GetUser().UserName;
                    contactAppt.ModifiedDate = DateTime.Now;
                    contactAppt.ModifiedUser = Membership.GetUser().UserName;
                    dataCtx.");

        
        #line default
        #line hidden
        
        #line 605 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 605 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"Appointments.AddObject(contactAppt);
                }
                else
                {
                    contactAppt.ModifiedDate = DateTime.Now;
                    contactAppt.ModifiedUser = Membership.GetUser().UserName;
                }
                dataCtx.SaveChanges();                
            }
        }
        protected void AppointmentsDataSource_Inserted(object sender, EntityDataSourceChangedEventArgs e)
        {
            SiteVisitAppointment apt = e.Entity as SiteVisitAppointment;
            if (apt == null)
                return;
            this.lastInsertedAppointmentId = apt.SiteVisitAppointmentID;
        }

    }
}
");

        
        #line default
        #line hidden
        
        #line 625 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"

    }

	private string GenerateSummaryExpression(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 631 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" + contact.");

        
        #line default
        #line hidden
        
        #line 631 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 631 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" + \" \"");

        
        #line default
        #line hidden
        
        #line 631 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}

	private string GenerateSummaryLabelsExpressions(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\tlbl");

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(".Text = (");

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.ControlType.CSTypeName));

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(")contact.");

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 639 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 640 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}

	private string GenerateLocationExpression(SiteVisitForm form)
	{
		AddressFieldHelper helper = new AddressFieldHelper(form);		

        
        #line default
        #line hidden
        
        #line 648 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetAddressSingleLine("contact")));

        
        #line default
        #line hidden
        
        #line 648 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		return "";
	}

	private string GenerateAddressExpression(SiteVisitForm form)
	{
		AddressFieldHelper helper = new AddressFieldHelper(form);
		string address2 = "";
		if (helper.Address2 != null)
		{
			address2 = "tbAddress2.Text = contact."+helper.Address2.FieldName+";";
		} else {
			address2 = "tbAddress2.Visible = false;";
		}

        
        #line default
        #line hidden
        
        #line 662 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\ttbAddress1.Text = contact.");

        
        #line default
        #line hidden
        
        #line 662 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.Address1.FieldName));

        
        #line default
        #line hidden
        
        #line 662 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 663 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(address2));

        
        #line default
        #line hidden
        
        #line 663 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\ttbCity.Text = contact.");

        
        #line default
        #line hidden
        
        #line 664 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.City.FieldName));

        
        #line default
        #line hidden
        
        #line 664 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n\t\t\ttbState.Text = contact.");

        
        #line default
        #line hidden
        
        #line 665 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.State.FieldName));

        
        #line default
        #line hidden
        
        #line 665 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n\t\t\ttbZip.Value = contact.");

        
        #line default
        #line hidden
        
        #line 666 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.Zip.FieldName));

        
        #line default
        #line hidden
        
        #line 666 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 667 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		return "";
	}

	private string GeneratePhoneExpression(SiteVisitForm form)
	{
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.ControlType.UITypeName == "PhoneNumber"
							select f);
		
		foreach (SiteVisitFormField phoneField in phoneFields)
		{

        
        #line default
        #line hidden
        
        #line 679 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\tuc");

        
        #line default
        #line hidden
        
        #line 679 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneField.FieldName));

        
        #line default
        #line hidden
        
        #line 679 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(".Value = contact.");

        
        #line default
        #line hidden
        
        #line 679 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneField.FieldName));

        
        #line default
        #line hidden
        
        #line 679 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 680 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}

	private string GenerateAddressSaveExpression(SiteVisitForm form)
	{
		AddressFieldHelper helper = new AddressFieldHelper(form);
		string address2 = "";
		if (helper.Address2 != null)
		{
			address2 = "contact."+helper.Address2.FieldName+" = (string)tbAddress2.Text;";
		} else {
			address2 = "";
		}

        
        #line default
        #line hidden
        
        #line 695 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\t\tcontact.");

        
        #line default
        #line hidden
        
        #line 695 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.Address1.FieldName));

        
        #line default
        #line hidden
        
        #line 695 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = (string)tbAddress1.Text;\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 696 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(address2));

        
        #line default
        #line hidden
        
        #line 696 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n\t\t\t\tcontact.");

        
        #line default
        #line hidden
        
        #line 697 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.City.FieldName));

        
        #line default
        #line hidden
        
        #line 697 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = (string)tbCity.Text;\r\n\t\t\t\tcontact.");

        
        #line default
        #line hidden
        
        #line 698 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.State.FieldName));

        
        #line default
        #line hidden
        
        #line 698 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = (string)tbState.Text;\r\n\t\t\t\tcontact.");

        
        #line default
        #line hidden
        
        #line 699 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(helper.Zip.FieldName));

        
        #line default
        #line hidden
        
        #line 699 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = (int?)tbZip.Value;\r\n");

        
        #line default
        #line hidden
        
        #line 700 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		return "";
	}

	private string GeneratePhoneSaveExpression(SiteVisitForm form)
	{
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.ControlType.UITypeName == "PhoneNumber"
							select f);
		
		foreach (SiteVisitFormField phoneField in phoneFields)
		{

        
        #line default
        #line hidden
        
        #line 712 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t\t\tcontact.");

        
        #line default
        #line hidden
        
        #line 712 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneField.FieldName));

        
        #line default
        #line hidden
        
        #line 712 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" = (string)uc");

        
        #line default
        #line hidden
        
        #line 712 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneField.FieldName));

        
        #line default
        #line hidden
        
        #line 712 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(".Value;\r\n");

        
        #line default
        #line hidden
        
        #line 713 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}
	private string GenerateDescriptionExpression(SiteVisitForm form, string sitevisitName)
	{
		AddressFieldHelper addressHelper = new AddressFieldHelper(form);

		var phoneFields = (from f in form.SiteVisitFormFields
							where f.ControlType.UITypeName == "PhoneNumber"
							select f);
		var summaryFields = SiteVisitDBHelper.GetSiteVisitSummaryFields(form);

		
		string summaryExpression = "";
		foreach (SiteVisitFormField phoneField in summaryFields)
		{
			summaryExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}

		string phoneExpression = "";
		foreach (SiteVisitFormField phoneField in phoneFields)
		{
			phoneExpression += "\"" + StringSanitizer.SanitizeForWeb(phoneField.FieldLabel) + ":\" + contact." + phoneField.FieldName + " + \"\\n\" + ";
		}


        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(summaryExpression));

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(phoneExpression));

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\"\\nAddress:\\n\" + ");

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressHelper.GetAddressFormatted("contact")));

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(" + \"\\n\\nGoogle Map:\\n\" + \"http://maps.google.com/maps?q=\" + Server.UrlEncode(");

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(addressHelper.GetAddressSingleLine("contact")));

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(") + \"\\n\\nSite Visit:\\n\" + \"http://\"+Request.Url.Authority+(string.IsNullOrEmpty(R" +
        "equest.ApplicationPath) ? \"\" : Request.ApplicationPath+\"/\") +\"SiteVisits/");

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("Edit.aspx?ID=\"+contactId");

        
        #line default
        #line hidden
        
        #line 739 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		return "";
	}

	void GenerateDesignerFile(SiteVisit sitevisit, IEnumerable<SiteVisitForm> forms)
	{
		string sitevisitName = sitevisit.SiteVisitName.Replace(" ", "");
		var parentForm = SiteVisitDBHelper.GetParentForm(sitevisit);
		string table = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBTableName;
        string pkey = sitevisit.SiteVisitName.Replace(" ", "") + "_" + parentForm.DBPrimaryKeyName;

        
        #line default
        #line hidden
        
        #line 749 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnSite.WebUI.Scheduler {
    
    
    public partial class ");

        
        #line default
        #line hidden
        
        #line 762 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(sitevisitName));

        
        #line default
        #line hidden
        
        #line 762 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"Edit {

		/// <summary>
        /// timezone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label timezone;

        /// <summary>
        /// ASPxSplitter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSplitter.ASPxSplitter ASPxSplitter1;
        
        /// <summary>
        /// ASPxGridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView ASPxGridView1;
		
        /// <summary>
        /// ");

        
        #line default
        #line hidden
        
        #line 792 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 792 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"ntityDataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.EntityDataSource ");

        
        #line default
        #line hidden
        
        #line 798 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table));

        
        #line default
        #line hidden
        
        #line 798 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("EntityDataSource;\r\n        \r\n        /// <summary>\r\n        /// SiteDataSource co" +
        "ntrol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generate" +
        "d field.\r\n        /// To modify move field declaration from designer file to cod" +
        "e-behind file.\r\n        /// </remarks>\r\n        protected global::System.Web.UI." +
        "WebControls.EntityDataSource SiteDataSource;\r\n        \r\n        /// <summary>\r\n " +
        "       /// ASPxScheduler1 control.\r\n        /// </summary>\r\n        /// <remarks" +
        ">\r\n        /// Auto-generated field.\r\n        /// To modify move field declarati" +
        "on from designer file to code-behind file.\r\n        /// </remarks>\r\n        prot" +
        "ected global::DevExpress.Web.ASPxScheduler.ASPxScheduler ASPxScheduler1;\r\n      " +
        "  \r\n        /// <summary>\r\n        /// ResourceDataSource control.\r\n        /// " +
        "</summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        //" +
        "/ To modify move field declaration from designer file to code-behind file.\r\n    " +
        "    /// </remarks>\r\n        protected global::System.Web.UI.WebControls.ObjectDa" +
        "taSource ResourceDataSource;\r\n        \r\n        /// <summary>\r\n        /// Appoi" +
        "ntmentsDataSource control.\r\n        /// </summary>\r\n        /// <remarks>\r\n     " +
        "   /// Auto-generated field.\r\n        /// To modify move field declaration from " +
        "designer file to code-behind file.\r\n        /// </remarks>\r\n        protected gl" +
        "obal::System.Web.UI.WebControls.EntityDataSource AppointmentsDataSource;\r\n\t\t\r\n\t\t" +
        "/// <summary>\r\n        /// DispositionsDataSource control.\r\n        /// </summar" +
        "y>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To mod" +
        "ify move field declaration from designer file to code-behind file.\r\n        /// " +
        "</remarks>\r\n        protected global::System.Web.UI.WebControls.EntityDataSource" +
        " DispositionsDataSource;\r\n\r\n        /// <summary>\r\n        /// cpSelectedSite co" +
        "ntrol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generate" +
        "d field.\r\n        /// To modify move field declaration from designer file to cod" +
        "e-behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web" +
        ".ASPxCallbackPanel.ASPxCallbackPanel cpSelectedSite;\r\n        \r\n        /// <sum" +
        "mary>\r\n        /// hf control.\r\n        /// </summary>\r\n        /// <remarks>\r\n " +
        "       /// Auto-generated field.\r\n        /// To modify move field declaration f" +
        "rom designer file to code-behind file.\r\n        /// </remarks>\r\n        protecte" +
        "d global::DevExpress.Web.ASPxHiddenField.ASPxHiddenField hf;\r\n        \r\n        " +
        "/// <summary>\r\n        /// lblSavedDate control.\r\n        /// </summary>\r\n      " +
        "  /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To modify move f" +
        "ield declaration from designer file to code-behind file.\r\n        /// </remarks>" +
        "\r\n        protected global::DevExpress.Web.ASPxEditors.ASPxLabel lblSavedDate;\r\n" +
        "        \r\n        /// <summary>\r\n        /// lblSavedBy control.\r\n        /// </" +
        "summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        /// " +
        "To modify move field declaration from designer file to code-behind file.\r\n      " +
        "  /// </remarks>\r\n        protected global::DevExpress.Web.ASPxEditors.ASPxLabel" +
        " lblSavedBy;\r\n                \r\n");

        
        #line default
        #line hidden
        
        #line 881 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GenerateSummaryProperties(parentForm)));

        
        #line default
        #line hidden
        
        #line 881 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\r\n        \r\n\t\t/// <summary>\r\n        /// tbAddress1 control.\r\n        /// </summa" +
        "ry>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n        /// To mo" +
        "dify move field declaration from designer file to code-behind file.\r\n        ///" +
        " </remarks>\r\n        protected global::DevExpress.Web.ASPxEditors.ASPxTextBox tb" +
        "Address1;\r\n        \r\n        /// <summary>\r\n        /// tbAddress2 control.\r\n   " +
        "     /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generated field.\r\n " +
        "       /// To modify move field declaration from designer file to code-behind fi" +
        "le.\r\n        /// </remarks>\r\n        protected global::DevExpress.Web.ASPxEditor" +
        "s.ASPxTextBox tbAddress2;\r\n        \r\n        /// <summary>\r\n        /// tbCity c" +
        "ontrol.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Auto-generat" +
        "ed field.\r\n        /// To modify move field declaration from designer file to co" +
        "de-behind file.\r\n        /// </remarks>\r\n        protected global::DevExpress.We" +
        "b.ASPxEditors.ASPxTextBox tbCity;\r\n        \r\n        /// <summary>\r\n        /// " +
        "tbState control.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// Aut" +
        "o-generated field.\r\n        /// To modify move field declaration from designer f" +
        "ile to code-behind file.\r\n        /// </remarks>\r\n        protected global::DevE" +
        "xpress.Web.ASPxEditors.ASPxTextBox tbState;\r\n        \r\n        /// <summary>\r\n  " +
        "      /// tbZip control.\r\n        /// </summary>\r\n        /// <remarks>\r\n       " +
        " /// Auto-generated field.\r\n        /// To modify move field declaration from de" +
        "signer file to code-behind file.\r\n        /// </remarks>\r\n        protected glob" +
        "al::OnSite.WebUI.UserControls.FormControls.ZipCode tbZip;\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 928 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratePhoneProperties(parentForm)));

        
        #line default
        #line hidden
        
        #line 928 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@"    

		/// <summary>
        /// cbDisposition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox cbDisposition;
        
        /// <summary>
        /// ASPxGridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView gridAppointments;
        
        /// <summary>
        /// SchedulerNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxMemo SchedulerNotes;

	}
}
");

        
        #line default
        #line hidden
        
        #line 959 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"

	}

	private string GenerateSummaryProperties(SiteVisitForm form)
	{
		foreach(SiteVisitFormField field in SiteVisitDBHelper.GetSiteVisitSummaryFields(form)) {

        
        #line default
        #line hidden
        
        #line 965 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t/// <summary>\r\n        /// lbl");

        
        #line default
        #line hidden
        
        #line 966 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 966 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@" control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxLabel lbl");

        
        #line default
        #line hidden
        
        #line 972 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 972 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 973 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}
	
	private string GeneratePhoneProperties(SiteVisitForm form)
	{
		var phoneFields = (from f in form.SiteVisitFormFields
							where f.ControlType.UITypeName == "PhoneNumber"
							select f);
		
		foreach (SiteVisitFormField field in phoneFields)
		{

        
        #line default
        #line hidden
        
        #line 986 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write("\t\t/// <summary>\r\n        /// uc");

        
        #line default
        #line hidden
        
        #line 987 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 987 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(@" control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnSite.WebUI.UserControls.FormControls.PhoneNumber uc");

        
        #line default
        #line hidden
        
        #line 993 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 993 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 994 "C:\Apps\On-Site\Admin\OnSite.TemplateWizard\T4\SchedulerEditTemplate.tt"
 
		}
		return "";
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class SchedulerEditTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
